In [1]:
import pandas as pd 
import numpy as np

In [2]:
wakep = pd.read_csv('../Data/wake-pitch.csv')

In [3]:
wakep

,Rk,Name,Age,W,L,W-L%,ERA,G,GS,GF,...,BK,WP,BF,WHIP,H9,HR9,BB9,SO9,SO/W,Notes
0,1.0,Will Andrews,22.0,0,0,NaN,0.00,3,0,NaN,...,0,0,10,0.375,0.0,0.0,3.4,10.1,3.00,NaN
1,2.0,Joe Ariola*,19.0,0,0,NaN,6.75,17,0,NaN,...,0,2,67,1.725,10.1,2.0,5.4,11.5,2.13,NaN
2,3.0,Derek Crum*,22.0,1,0,1.000,3.38,19,0,NaN,...,0,1,69,1.250,9.0,0.0,2.3,7.9,3.50,NaN
3,4.0,Josh Hartle*,20.0,11,2,0.846,2.80,17,16,NaN,...,1,7,394,1.111,8.1,1.0,1.9,12.2,6.55,NaN
4,5.0,Zach Johnston*,19.0,0,0,NaN,6.75,4,0,NaN,...,0,0,16,3.000,10.1,0.0,16.9,13.5,0.80,NaN
5,6.0,Seth Keener,21.0,7,1,0.875,2.23,21,7,NaN,...,1,4,255,0.820,5.1,0.4,2.2,12.0,5.38,NaN
6,7.0,Rhett Lowder,21.0,15,0,1.000,1.92,17,17,NaN,...,0,2,420,0.935,6.7,0.8,1.8,10.9,6.24,NaN
7,8.0,Reed Mascolo,23.0,7,1,0.875,3.96,14,11,NaN,...,1,4,212,1.220,8.8,1.8,2.2,7.9,3.67,NaN
8,9.0,Michael Massey,20.0,3,0,1.000,2.58,25,1,NaN,...,1,1,147,0.939,4.9,1.4,3.5,16.7,4.73,NaN
9,10.0,Cam Minacci,21.0,0,1,0.000,2.73,27,0,NaN,...,0,3,126,1.180,7.6,0.9,3.0,13.3,4.40,NaN
10,11.0,Will Ray,21.0,1,1,0.500,5.40,18,0,NaN,...,0,0,51,1.286,4.6,2.3,6.9,6.9,1.00,NaN
11,12.0,Cole Roland,24.0,2,1,0.667,2.12,24,0,NaN,...,3,3,121,0.910,4.6,1.2,3.6,15.8,4.33,NaN
12,13.0,Ben Shenosky,19.0,0,0,NaN,11.57,6,0,NaN,...,0,1,24,2.143,3.9,3.9,15.4,15.4,1.00,NaN
13,14.0,Sean Sullivan*,20.0,5,3,0.625,2.64,15,10,NaN,...,0,3,260,0.881,5.4,1.1,2.5,15.0,6.00,NaN
14,15.0,Crawford Wade*,21.0,0,0,NaN,0.00,2,0,NaN,...,0,0,13,0.273,2.5,0.0,0.0,9.8,NaN,NaN
15,16.0,Chase Walter,23.0,0,0,NaN,3.72,13,0,NaN,...,0,2,44,1.241,4.7,0.0,6.5,11.2,1.71,NaN
16,NaN,16 Players,21.1,52,10,0.839,2.84,62,62,NaN,...,7,33,2229,1.039,6.6,1.0,2.7,12.2,4.45,NaN

In [4]:
wakeb = pd.read_csv('../Data/wake-bat.csv')

In [5]:
wakeb

,Rk,Name,Age,G,PA,AB,R,H,2B,3B,...,OBP,SLG,OPS,TB,GDP,HBP,SH,SF,IBB,Notes
0,1.0,Pierce Bennett,22.0,56,263,221,59,79,19,0,...,0.434,0.539,0.973,119,NaN,7,5,4,NaN,NaN
1,2.0,Adam Cecere*,22.0,40,172,135,40,39,11,0,...,0.436,0.593,1.029,80,NaN,6,0,1,NaN,NaN
2,3.0,Danny Corona*,19.0,44,159,136,28,41,9,0,...,0.378,0.654,1.033,89,NaN,3,3,2,NaN,NaN
3,4.0,Lucas Costello,21.0,45,188,155,43,47,9,1,...,0.410,0.452,0.861,70,NaN,11,5,0,NaN,NaN
4,5.0,Gio Cueto,19.0,32,98,78,14,15,4,0,...,0.337,0.321,0.657,25,NaN,7,0,2,NaN,NaN
5,6.0,Tommy Hawke*,20.0,62,309,254,72,90,19,1,...,0.466,0.520,0.986,132,NaN,4,0,1,NaN,NaN
6,7.0,Marek Houston,19.0,61,245,205,38,46,5,1,...,0.332,0.317,0.649,65,NaN,2,4,2,NaN,NaN
7,8.0,Justin Johnson,23.0,61,276,223,60,76,15,3,...,0.442,0.650,1.092,145,NaN,13,2,6,NaN,NaN
8,9.0,Kyle Joye,24.0,17,46,39,13,11,4,0,...,0.391,0.539,0.930,21,NaN,2,0,0,NaN,NaN
9,10.0,Chris Katz,20.0,26,78,63,10,13,4,0,...,0.346,0.413,0.759,26,NaN,1,0,1,NaN,NaN
10,11.0,Nick Kurtz*,20.0,53,252,181,75,67,10,0,...,0.538,0.823,1.361,149,NaN,9,1,2,NaN,NaN
11,12.0,Bennett Lee,21.0,42,170,130,29,40,3,0,...,0.438,0.492,0.930,64,NaN,5,1,5,NaN,NaN
12,13.0,Andrew Noland#,19.0,7,11,10,1,2,0,0,...,0.273,0.200,0.473,2,NaN,0,0,0,NaN,NaN
13,14.0,Jake Reinisch*,21.0,27,91,73,8,13,1,0,...,0.308,0.192,0.500,14,NaN,0,0,3,NaN,NaN
14,15.0,Brock Wilken,21.0,62,302,224,88,80,15,1,...,0.517,0.835,1.351,187,NaN,11,0,2,NaN,NaN
15,16.0,Jack Winnay,20.0,15,22,15,5,3,0,0,...,0.455,0.200,0.655,3,NaN,3,0,0,NaN,NaN
16,NaN,16 Players,20.8,62,2682,2142,583,662,128,7,...,0.432,0.556,0.988,1191,NaN,84,21,31,NaN,NaN

In [6]:
wakep = wakep.drop(columns=['BK', 'IBB', 'W-L%', 'GF', 'CG', 'Rk', 'Notes'])
wakep

,Name,Age,W,L,ERA,G,GS,SHO,SV,IP,...,SO,HBP,WP,BF,WHIP,H9,HR9,BB9,SO9,SO/W
0,Will Andrews,22.0,0,0,0.00,3,0,0,0,2.2,...,3,1,0,10,0.375,0.0,0.0,3.4,10.1,3.00
1,Joe Ariola*,19.0,0,0,6.75,17,0,0,0,13.1,...,17,3,2,67,1.725,10.1,2.0,5.4,11.5,2.13
2,Derek Crum*,22.0,1,0,3.38,19,0,0,0,16.0,...,14,4,1,69,1.250,9.0,0.0,2.3,7.9,3.50
3,Josh Hartle*,20.0,11,2,2.80,17,16,0,0,96.1,...,131,5,7,394,1.111,8.1,1.0,1.9,12.2,6.55
4,Zach Johnston*,19.0,0,0,6.75,4,0,0,0,2.2,...,4,0,0,16,3.000,10.1,0.0,16.9,13.5,0.80
5,Seth Keener,21.0,7,1,2.23,21,7,0,1,64.2,...,86,10,4,255,0.820,5.1,0.4,2.2,12.0,5.38
6,Rhett Lowder,21.0,15,0,1.92,17,17,0,0,108.0,...,131,9,2,420,0.935,6.7,0.8,1.8,10.9,6.24
7,Reed Mascolo,23.0,7,1,3.96,14,11,0,0,50.0,...,44,8,4,212,1.220,8.8,1.8,2.2,7.9,3.67
8,Michael Massey,20.0,3,0,2.58,25,1,0,1,38.1,...,71,0,1,147,0.939,4.9,1.4,3.5,16.7,4.73
9,Cam Minacci,21.0,0,1,2.73,27,0,0,12,29.2,...,44,2,3,126,1.180,7.6,0.9,3.0,13.3,4.40
10,Will Ray,21.0,1,1,5.40,18,0,0,0,11.2,...,9,1,0,51,1.286,4.6,2.3,6.9,6.9,1.00
11,Cole Roland,24.0,2,1,2.12,24,0,0,2,29.2,...,52,4,3,121,0.910,4.6,1.2,3.6,15.8,4.33
12,Ben Shenosky,19.0,0,0,11.57,6,0,0,0,4.2,...,8,0,1,24,2.143,3.9,3.9,15.4,15.4,1.00
13,Sean Sullivan*,20.0,5,3,2.64,15,10,0,3,64.2,...,108,11,3,260,0.881,5.4,1.1,2.5,15.0,6.00
14,Crawford Wade*,21.0,0,0,0.00,2,0,0,0,3.2,...,4,1,0,13,0.273,2.5,0.0,0.0,9.8,NaN
15,Chase Walter,23.0,0,0,3.72,13,0,0,0,9.2,...,12,2,2,44,1.241,4.7,0.0,6.5,11.2,1.71
16,16 Players,21.1,52,10,2.84,62,62,10,19,545.2,...,738,61,33,2229,1.039,6.6,1.0,2.7,12.2,4.45

In [7]:
wakep = wakep.sort_values(by=['BF'], ascending=False)
wakep

,Name,Age,W,L,ERA,G,GS,SHO,SV,IP,...,SO,HBP,WP,BF,WHIP,H9,HR9,BB9,SO9,SO/W
16,16 Players,21.1,52,10,2.84,62,62,10,19,545.2,...,738,61,33,2229,1.039,6.6,1.0,2.7,12.2,4.45
6,Rhett Lowder,21.0,15,0,1.92,17,17,0,0,108.0,...,131,9,2,420,0.935,6.7,0.8,1.8,10.9,6.24
3,Josh Hartle*,20.0,11,2,2.80,17,16,0,0,96.1,...,131,5,7,394,1.111,8.1,1.0,1.9,12.2,6.55
13,Sean Sullivan*,20.0,5,3,2.64,15,10,0,3,64.2,...,108,11,3,260,0.881,5.4,1.1,2.5,15.0,6.00
5,Seth Keener,21.0,7,1,2.23,21,7,0,1,64.2,...,86,10,4,255,0.820,5.1,0.4,2.2,12.0,5.38
7,Reed Mascolo,23.0,7,1,3.96,14,11,0,0,50.0,...,44,8,4,212,1.220,8.8,1.8,2.2,7.9,3.67
8,Michael Massey,20.0,3,0,2.58,25,1,0,1,38.1,...,71,0,1,147,0.939,4.9,1.4,3.5,16.7,4.73
9,Cam Minacci,21.0,0,1,2.73,27,0,0,12,29.2,...,44,2,3,126,1.180,7.6,0.9,3.0,13.3,4.40
11,Cole Roland,24.0,2,1,2.12,24,0,0,2,29.2,...,52,4,3,121,0.910,4.6,1.2,3.6,15.8,4.33
2,Derek Crum*,22.0,1,0,3.38,19,0,0,0,16.0,...,14,4,1,69,1.250,9.0,0.0,2.3,7.9,3.50
1,Joe Ariola*,19.0,0,0,6.75,17,0,0,0,13.1,...,17,3,2,67,1.725,10.1,2.0,5.4,11.5,2.13
10,Will Ray,21.0,1,1,5.40,18,0,0,0,11.2,...,9,1,0,51,1.286,4.6,2.3,6.9,6.9,1.00
15,Chase Walter,23.0,0,0,3.72,13,0,0,0,9.2,...,12,2,2,44,1.241,4.7,0.0,6.5,11.2,1.71
12,Ben Shenosky,19.0,0,0,11.57,6,0,0,0,4.2,...,8,0,1,24,2.143,3.9,3.9,15.4,15.4,1.00
4,Zach Johnston*,19.0,0,0,6.75,4,0,0,0,2.2,...,4,0,0,16,3.000,10.1,0.0,16.9,13.5,0.80
14,Crawford Wade*,21.0,0,0,0.00,2,0,0,0,3.2,...,4,1,0,13,0.273,2.5,0.0,0.0,9.8,NaN
0,Will Andrews,22.0,0,0,0.00,3,0,0,0,2.2,...,3,1,0,10,0.375,0.0,0.0,3.4,10.1,3.00

In [9]:
wakep = wakep[1:]

In [10]:
wakeb

,Rk,Name,Age,G,PA,AB,R,H,2B,3B,...,OBP,SLG,OPS,TB,GDP,HBP,SH,SF,IBB,Notes
0,1.0,Pierce Bennett,22.0,56,263,221,59,79,19,0,...,0.434,0.539,0.973,119,NaN,7,5,4,NaN,NaN
1,2.0,Adam Cecere*,22.0,40,172,135,40,39,11,0,...,0.436,0.593,1.029,80,NaN,6,0,1,NaN,NaN
2,3.0,Danny Corona*,19.0,44,159,136,28,41,9,0,...,0.378,0.654,1.033,89,NaN,3,3,2,NaN,NaN
3,4.0,Lucas Costello,21.0,45,188,155,43,47,9,1,...,0.410,0.452,0.861,70,NaN,11,5,0,NaN,NaN
4,5.0,Gio Cueto,19.0,32,98,78,14,15,4,0,...,0.337,0.321,0.657,25,NaN,7,0,2,NaN,NaN
5,6.0,Tommy Hawke*,20.0,62,309,254,72,90,19,1,...,0.466,0.520,0.986,132,NaN,4,0,1,NaN,NaN
6,7.0,Marek Houston,19.0,61,245,205,38,46,5,1,...,0.332,0.317,0.649,65,NaN,2,4,2,NaN,NaN
7,8.0,Justin Johnson,23.0,61,276,223,60,76,15,3,...,0.442,0.650,1.092,145,NaN,13,2,6,NaN,NaN
8,9.0,Kyle Joye,24.0,17,46,39,13,11,4,0,...,0.391,0.539,0.930,21,NaN,2,0,0,NaN,NaN
9,10.0,Chris Katz,20.0,26,78,63,10,13,4,0,...,0.346,0.413,0.759,26,NaN,1,0,1,NaN,NaN
10,11.0,Nick Kurtz*,20.0,53,252,181,75,67,10,0,...,0.538,0.823,1.361,149,NaN,9,1,2,NaN,NaN
11,12.0,Bennett Lee,21.0,42,170,130,29,40,3,0,...,0.438,0.492,0.930,64,NaN,5,1,5,NaN,NaN
12,13.0,Andrew Noland#,19.0,7,11,10,1,2,0,0,...,0.273,0.200,0.473,2,NaN,0,0,0,NaN,NaN
13,14.0,Jake Reinisch*,21.0,27,91,73,8,13,1,0,...,0.308,0.192,0.500,14,NaN,0,0,3,NaN,NaN
14,15.0,Brock Wilken,21.0,62,302,224,88,80,15,1,...,0.517,0.835,1.351,187,NaN,11,0,2,NaN,NaN
15,16.0,Jack Winnay,20.0,15,22,15,5,3,0,0,...,0.455,0.200,0.655,3,NaN,3,0,0,NaN,NaN
16,NaN,16 Players,20.8,62,2682,2142,583,662,128,7,...,0.432,0.556,0.988,1191,NaN,84,21,31,NaN,NaN

In [11]:
wakeb = wakeb.drop(columns=['IBB', 'Notes', 'Rk', 'SH', 'CS', 'SB', 'GDP'])
wakeb

,Name,Age,G,PA,AB,R,H,2B,3B,HR,RBI,BB,SO,BA,OBP,SLG,OPS,TB,HBP,SF
0,Pierce Bennett,22.0,56,263,221,59,79,19,0,7,65,26,21,0.358,0.434,0.539,0.973,119,7,4
1,Adam Cecere*,22.0,40,172,135,40,39,11,0,10,37,30,49,0.289,0.436,0.593,1.029,80,6,1
2,Danny Corona*,19.0,44,159,136,28,41,9,0,13,43,15,45,0.302,0.378,0.654,1.033,89,3,2
3,Lucas Costello,21.0,45,188,155,43,47,9,1,4,24,17,28,0.303,0.410,0.452,0.861,70,11,0
4,Gio Cueto,19.0,32,98,78,14,15,4,0,2,8,11,15,0.192,0.337,0.321,0.657,25,7,2
5,Tommy Hawke*,20.0,62,309,254,72,90,19,1,7,33,50,48,0.354,0.466,0.520,0.986,132,4,1
6,Marek Houston,19.0,61,245,205,38,46,5,1,4,29,32,38,0.224,0.332,0.317,0.649,65,2,2
7,Justin Johnson,23.0,61,276,223,60,76,15,3,16,76,32,42,0.341,0.442,0.650,1.092,145,13,6
8,Kyle Joye,24.0,17,46,39,13,11,4,0,2,10,5,10,0.282,0.391,0.539,0.930,21,2,0
9,Chris Katz,20.0,26,78,63,10,13,4,0,3,16,13,15,0.206,0.346,0.413,0.759,26,1,1
10,Nick Kurtz*,20.0,53,252,181,75,67,10,0,24,69,59,45,0.370,0.538,0.823,1.361,149,9,2
11,Bennett Lee,21.0,42,170,130,29,40,3,0,7,33,29,28,0.308,0.438,0.492,0.930,64,5,5
12,Andrew Noland#,19.0,7,11,10,1,2,0,0,0,1,1,4,0.200,0.273,0.200,0.473,2,0,0
13,Jake Reinisch*,21.0,27,91,73,8,13,1,0,0,9,15,22,0.178,0.308,0.192,0.500,14,0,3
14,Brock Wilken,21.0,62,302,224,88,80,15,1,30,80,65,51,0.357,0.517,0.835,1.351,187,11,2
15,Jack Winnay,20.0,15,22,15,5,3,0,0,0,1,4,4,0.200,0.455,0.200,0.655,3,3,0
16,16 Players,20.8,62,2682,2142,583,662,128,7,129,534,404,465,0.309,0.432,0.556,0.988,1191,84,31

In [12]:
wakeb = wakeb.sort_values(by=['PA'], ascending=False)
wakeb

,Name,Age,G,PA,AB,R,H,2B,3B,HR,RBI,BB,SO,BA,OBP,SLG,OPS,TB,HBP,SF
16,16 Players,20.8,62,2682,2142,583,662,128,7,129,534,404,465,0.309,0.432,0.556,0.988,1191,84,31
5,Tommy Hawke*,20.0,62,309,254,72,90,19,1,7,33,50,48,0.354,0.466,0.520,0.986,132,4,1
14,Brock Wilken,21.0,62,302,224,88,80,15,1,30,80,65,51,0.357,0.517,0.835,1.351,187,11,2
7,Justin Johnson,23.0,61,276,223,60,76,15,3,16,76,32,42,0.341,0.442,0.650,1.092,145,13,6
0,Pierce Bennett,22.0,56,263,221,59,79,19,0,7,65,26,21,0.358,0.434,0.539,0.973,119,7,4
10,Nick Kurtz*,20.0,53,252,181,75,67,10,0,24,69,59,45,0.370,0.538,0.823,1.361,149,9,2
6,Marek Houston,19.0,61,245,205,38,46,5,1,4,29,32,38,0.224,0.332,0.317,0.649,65,2,2
3,Lucas Costello,21.0,45,188,155,43,47,9,1,4,24,17,28,0.303,0.410,0.452,0.861,70,11,0
1,Adam Cecere*,22.0,40,172,135,40,39,11,0,10,37,30,49,0.289,0.436,0.593,1.029,80,6,1
11,Bennett Lee,21.0,42,170,130,29,40,3,0,7,33,29,28,0.308,0.438,0.492,0.930,64,5,5
2,Danny Corona*,19.0,44,159,136,28,41,9,0,13,43,15,45,0.302,0.378,0.654,1.033,89,3,2
4,Gio Cueto,19.0,32,98,78,14,15,4,0,2,8,11,15,0.192,0.337,0.321,0.657,25,7,2
13,Jake Reinisch*,21.0,27,91,73,8,13,1,0,0,9,15,22,0.178,0.308,0.192,0.500,14,0,3
9,Chris Katz,20.0,26,78,63,10,13,4,0,3,16,13,15,0.206,0.346,0.413,0.759,26,1,1
8,Kyle Joye,24.0,17,46,39,13,11,4,0,2,10,5,10,0.282,0.391,0.539,0.930,21,2,0
15,Jack Winnay,20.0,15,22,15,5,3,0,0,0,1,4,4,0.200,0.455,0.200,0.655,3,3,0
12,Andrew Noland#,19.0,7,11,10,1,2,0,0,0,1,1,4,0.200,0.273,0.200,0.473,2,0,0

In [14]:
wakeb = wakeb[1:]

In [15]:
wakeb

,Name,Age,G,PA,AB,R,H,2B,3B,HR,RBI,BB,SO,BA,OBP,SLG,OPS,TB,HBP,SF
5,Tommy Hawke*,20.0,62,309,254,72,90,19,1,7,33,50,48,0.354,0.466,0.520,0.986,132,4,1
14,Brock Wilken,21.0,62,302,224,88,80,15,1,30,80,65,51,0.357,0.517,0.835,1.351,187,11,2
7,Justin Johnson,23.0,61,276,223,60,76,15,3,16,76,32,42,0.341,0.442,0.650,1.092,145,13,6
0,Pierce Bennett,22.0,56,263,221,59,79,19,0,7,65,26,21,0.358,0.434,0.539,0.973,119,7,4
10,Nick Kurtz*,20.0,53,252,181,75,67,10,0,24,69,59,45,0.370,0.538,0.823,1.361,149,9,2
6,Marek Houston,19.0,61,245,205,38,46,5,1,4,29,32,38,0.224,0.332,0.317,0.649,65,2,2
3,Lucas Costello,21.0,45,188,155,43,47,9,1,4,24,17,28,0.303,0.410,0.452,0.861,70,11,0
1,Adam Cecere*,22.0,40,172,135,40,39,11,0,10,37,30,49,0.289,0.436,0.593,1.029,80,6,1
11,Bennett Lee,21.0,42,170,130,29,40,3,0,7,33,29,28,0.308,0.438,0.492,0.930,64,5,5
2,Danny Corona*,19.0,44,159,136,28,41,9,0,13,43,15,45,0.302,0.378,0.654,1.033,89,3,2
4,Gio Cueto,19.0,32,98,78,14,15,4,0,2,8,11,15,0.192,0.337,0.321,0.657,25,7,2
13,Jake Reinisch*,21.0,27,91,73,8,13,1,0,0,9,15,22,0.178,0.308,0.192,0.500,14,0,3
9,Chris Katz,20.0,26,78,63,10,13,4,0,3,16,13,15,0.206,0.346,0.413,0.759,26,1,1
8,Kyle Joye,24.0,17,46,39,13,11,4,0,2,10,5,10,0.282,0.391,0.539,0.930,21,2,0
15,Jack Winnay,20.0,15,22,15,5,3,0,0,0,1,4,4,0.200,0.455,0.200,0.655,3,3,0
12,Andrew Noland#,19.0,7,11,10,1,2,0,0,0,1,1,4,0.200,0.273,0.200,0.473,2,0,0