In [1]:
import pandas as pd
import numpy as np

In [5]:
wc19melb = pd.read_csv('../../Cleaning/qual_events/men/wc19bmelb_fx.csv')
wc20baku = pd.read_csv('../../Cleaning/qual_events/men/wc20baku_fx.csv')
world18 = pd.read_csv('../../Cleaning/qual_events/men/world18championship_fx.csv')

In [6]:
fx = pd.concat([wc19melb, wc20baku, world18])

In [7]:
fx

     Rank              Athlete Nation    D      E   ND   Total  year  round
0       1   carlos edriel yulo    PHI  6.2  8.366  0.0  14.566  2019  final
1       2    hibiki arayashiki    JPN  5.9  8.600  0.0  14.500  2019  final
2       3     rayderley zapata    ESP  6.1  8.400  0.0  14.500  2019  final
3       3  dominick cunningham   none  6.1  8.400  0.0  14.500  2019  final
4       5          kim han-sol    SKR  6.2  8.000  0.0  14.200  2019  final
..    ...                  ...    ...  ...    ...  ...     ...   ...    ...
204   196           ahmed mosa    QAT  4.3  6.200  0.0  10.500  2018   qual
205   197       timur bairamov    AZE  3.9  6.533  0.0  10.433  2018   qual
206   198        han chung hyo   none  2.7  6.566  0.0   9.266  2018   qual
207   199     wei an terry tay    SIN  4.1  5.166 -0.2   9.066  2018   qual
208   200  abdullah al-dulaimi    IRQ  3.6  4.033 -0.2   7.433  2018   qual

[281 rows x 9 columns]