In [1]:
import numpy as np
import pandas as pd

In [2]:
pit = pd.read_csv('pitch.csv')
bat = pd.read_csv('batting_clean.csv')

In [3]:
bat.head()

,R/G,G,PA,AB,R,H,2B,3B,HR,RBI,...,OBP,SLG,OPS,TB,HBP,SF,year,tm_code,W,L
0,5.01,162,6224,5525,812,1405,314,39,220,776,...,0.329,0.445,0.774,2457,54,27,2017,0,93,69
1,4.52,162,6216,5584,732,1467,289,26,165,706,...,0.326,0.412,0.738,2303,66,32,2017,1,72,90
2,4.59,162,6140,5650,743,1469,269,12,232,713,...,0.312,0.435,0.747,2458,50,37,2017,2,75,87
3,4.85,162,6338,5669,785,1461,302,19,168,735,...,0.329,0.407,0.736,2305,53,36,2017,3,93,69
4,5.07,162,6283,5496,822,1402,274,29,223,785,...,0.338,0.437,0.775,2403,82,32,2017,4,92,70

In [4]:
bat_test = bat[bat['year'] == 2022]

In [5]:
bat_train = bat[:120]

In [6]:
y_train = bat_train['W']
y_train

0       93
1       72
2       75
3       93
4       92
      ...
115     90
116    100
117     60
118     91
119     65
Name: W, Length: 120, dtype: int64

In [7]:
x_train = bat_train.drop(columns=['W'])
x_train

,R/G,G,PA,AB,R,H,2B,3B,HR,RBI,...,BA,OBP,SLG,OPS,TB,HBP,SF,year,tm_code,L
0,5.01,162,6224,5525,812,1405,314,39,220,776,...,0.254,0.329,0.445,0.774,2457,54,27,2017,0,69
1,4.52,162,6216,5584,732,1467,289,26,165,706,...,0.263,0.326,0.412,0.738,2303,66,32,2017,1,90
2,4.59,162,6140,5650,743,1469,269,12,232,713,...,0.260,0.312,0.435,0.747,2458,50,37,2017,2,87
3,4.85,162,6338,5669,785,1461,302,19,168,735,...,0.258,0.329,0.407,0.736,2305,53,36,2017,3,69
4,5.07,162,6283,5496,822,1402,274,29,223,785,...,0.255,0.338,0.437,0.775,2403,82,32,2017,4,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,4.36,162,6001,5351,706,1303,261,22,198,678,...,0.244,0.313,0.412,0.725,2202,86,44,2021,26,72
116,5.29,162,6213,5507,857,1336,288,36,222,810,...,0.243,0.321,0.429,0.750,2362,72,41,2021,27,62
117,3.86,162,5943,5405,625,1254,225,24,167,598,...,0.232,0.294,0.375,0.670,2028,58,31,2021,28,102
118,5.22,162,6070,5476,846,1455,285,13,262,816,...,0.266,0.330,0.466,0.797,2552,51,35,2021,29,71
119,4.47,162,6113,5385,724,1388,272,20,182,686,...,0.258,0.337,0.417,0.754,2246,84,31,2021,30,97

In [8]:
x_train.describe()

,R/G,G,PA,AB,R,H,2B,3B,HR,RBI,...,BA,OBP,SLG,OPS,TB,HBP,SF,year,tm_code,L
count,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,...,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000
mean,4.614667,161.983333,6156.433333,5496.591667,747.408333,1372.966667,275.458333,25.816667,203.416667,713.566667,...,0.249667,0.320408,0.420083,0.740525,2310.308333,64.841667,39.133333,2018.750000,15.266667,80.991667
std,0.481678,0.289402,114.643674,92.184643,78.238645,76.238782,28.918865,8.269599,36.047257,76.165315,...,0.010740,0.012486,0.026468,0.037315,168.212041,15.182916,7.294447,1.485221,9.007684,14.001498
min,3.610000,161.000000,5856.000000,5210.000000,582.000000,1209.000000,213.000000,5.000000,124.000000,554.000000,...,0.226000,0.294000,0.357000,0.659000,1943.000000,31.000000,23.000000,2017.000000,0.000000,54.000000
25%,4.300000,162.000000,6075.250000,5443.000000,695.500000,1319.250000,255.000000,20.000000,178.250000,664.750000,...,0.241000,0.312000,0.403500,0.717750,2188.750000,53.750000,34.000000,2017.750000,8.000000,70.750000
50%,4.575000,162.000000,6154.000000,5498.500000,739.000000,1369.000000,273.500000,24.500000,205.500000,708.500000,...,0.249000,0.320500,0.421000,0.740000,2316.500000,64.000000,39.000000,2018.500000,15.500000,82.000000
75%,4.937500,162.000000,6241.250000,5551.500000,804.000000,1428.250000,292.000000,31.000000,224.000000,765.500000,...,0.257250,0.329000,0.435000,0.761750,2412.000000,73.000000,44.000000,2019.500000,23.000000,91.000000
max,5.820000,163.000000,6475.000000,5770.000000,943.000000,1581.000000,355.000000,50.000000,307.000000,906.000000,...,0.282000,0.352000,0.495000,0.848000,2832.000000,105.000000,61.000000,2021.000000,30.000000,115.000000

In [9]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 22 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   R/G      120 non-null    float64
 1   G        120 non-null    int64
 2   PA       120 non-null    int64
 3   AB       120 non-null    int64
 4   R        120 non-null    int64
 5   H        120 non-null    int64
 6   2B       120 non-null    int64
 7   3B       120 non-null    int64
 8   HR       120 non-null    int64
 9   RBI      120 non-null    int64
 10  BB       120 non-null    int64
 11  SO       120 non-null    int64
 12  BA       120 non-null    float64
 13  OBP      120 non-null    float64
 14  SLG      120 non-null    float64
 15  OPS      120 non-null    float64
 16  TB       120 non-null    int64
 17  HBP      120 non-null    int64
 18  SF       120 non-null    int64
 19  year     120 non-null    int64
 20  tm_code  120 non-null    int64
 21  L        120 non-null    int64
dtypes: float64(5), int64(17)
memory usage: 20.8 KB

In [10]:
bat_test

,R/G,G,PA,AB,R,H,2B,3B,HR,RBI,...,OBP,SLG,OPS,TB,HBP,SF,year,tm_code,W,L
120,4.33,162,6027,5351,702,1232,262,24,173,658,...,0.304,0.385,0.689,2061,60,50,2022,0,74,88
121,4.87,162,6082,5509,789,1394,298,11,243,753,...,0.317,0.443,0.761,2443,66,36,2022,1,101,61
122,4.16,162,6049,5429,674,1281,275,25,171,639,...,0.305,0.390,0.695,2119,83,43,2022,2,83,79
123,4.54,162,6144,5539,735,1427,352,12,155,704,...,0.321,0.409,0.731,2268,63,50,2022,3,78,84
124,4.06,162,6072,5425,657,1293,265,31,159,620,...,0.311,0.387,0.698,2097,84,36,2022,4,74,88
125,4.23,162,6123,5611,686,1435,272,9,149,654,...,0.310,0.387,0.698,2172,73,35,2022,5,81,81
126,4.00,162,5978,5380,648,1264,235,18,156,618,...,0.304,0.372,0.676,2003,92,33,2022,6,62,100
127,4.31,162,6163,5558,698,1410,273,31,127,662,...,0.316,0.383,0.699,2126,81,52,2022,7,92,70
128,4.31,162,6105,5540,698,1408,280,34,149,669,...,0.315,0.398,0.713,2203,61,40,2022,9,68,94
129,3.44,162,5870,5378,557,1240,235,27,110,530,...,0.286,0.346,0.632,1859,58,44,2022,10,66,96
130,4.55,162,6054,5409,737,1341,284,13,214,715,...,0.319,0.424,0.743,2293,60,42,2022,11,106,56
131,3.95,162,6010,5437,640,1327,247,38,138,613,...,0.306,0.380,0.686,2064,48,44,2022,12,65,97
132,3.85,162,5977,5423,623,1265,219,31,190,600,...,0.297,0.390,0.687,2116,54,25,2022,13,73,89
133,5.23,162,6247,5526,847,1418,325,31,212,812,...,0.333,0.442,0.775,2441,56,53,2022,14,111,51
134,3.62,162,5949,5395,586,1241,248,20,144,554,...,0.294,0.363,0.658,1961,70,36,2022,15,69,93
135,4.48,162,6122,5417,725,1271,251,17,219,703,...,0.315,0.409,0.724,2213,80,37,2022,16,86,76
136,4.30,162,6113,5476,696,1356,269,18,178,668,...,0.317,0.401,0.718,2195,62,46,2022,17,78,84
137,4.77,162,6176,5489,772,1422,272,27,171,735,...,0.332,0.412,0.744,2261,112,44,2022,18,101,61
138,4.98,162,6172,5422,807,1308,225,8,254,764,...,0.325,0.426,0.751,2311,70,41,2022,19,99,63
139,3.51,162,5863,5314,568,1147,249,15,137,537,...,0.281,0.346,0.626,1837,59,33,2022,20,60,102
140,4.61,162,6077,5496,747,1392,255,29,205,719,...,0.317,0.422,0.739,2320,52,44,2022,21,87,75
141,3.65,162,5912,5331,591,1186,221,29,158,555,...,0.291,0.364,0.655,1939,54,32,2022,22,62,100
142,4.35,162,6175,5468,705,1317,275,18,153,682,...,0.318,0.382,0.700,2087,65,46,2022,23,89,73
143,4.26,162,6117,5375,690,1236,229,19,197,663,...,0.315,0.390,0.704,2094,89,45,2022,25,90,72
144,4.42,162,6117,5392,716,1261,255,18,183,683,...,0.315,0.390,0.705,2101,95,53,2022,24,81,81
145,4.77,162,6165,5496,772,1386,290,21,197,739,...,0.325,0.420,0.745,2309,80,45,2022,26,93,69
146,4.11,162,6008,5412,666,1294,296,17,139,634,...,0.309,0.377,0.686,2041,57,31,2022,27,86,76
147,4.36,162,6029,5478,707,1308,224,20,198,670,...,0.301,0.395,0.696,2166,47,38,2022,28,68,94
148,4.78,162,6158,5555,775,1464,307,12,200,756,...,0.329,0.431,0.760,2395,55,33,2022,29,92,70
149,3.72,162,5998,5434,603,1351,252,20,136,579,...,0.310,0.377,0.688,2051,60,37,2022,30,55,107

In [11]:
ytest = bat_test["W"]
xtest = bat_test.drop(columns=["W"])

In [12]:
from sklearn import linear_model
from sklearn import svm
from sklearn.svm import SVR
import matplotlib.pyplot as plt

In [13]:
regr = svm.SVR()
regr.fit(x_train, y_train)
SVR()

SVR()

In [14]:
regr.predict(xtest, ytest)

TypeError: predict() takes 2 positional arguments but 3 were given

In [15]:
import numpy as np
from sklearn.linear_model import SGDRegressor
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

In [17]:
# Always scale the input. The most convenient way is to use a pipeline.
reg = make_pipeline(StandardScaler(),
                    SGDRegressor(max_iter=1000, tol=1e-3))
reg.fit(x_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('sgdregressor', SGDRegressor())])

In [21]:
predictions=reg.predict(xtest)
predictions

array([ 74.1971025 , 100.45497612,  82.57970877,  77.81370664,
        73.55764703,  80.55819161,  62.16563158,  91.50223901,
        67.79945444,  65.81231221, 105.17845991,  64.75029233,
        72.32863245, 110.6438861 ,  68.57639939,  85.65294945,
        77.58870391, 100.66321403,  98.85070277,  60.07104508,
        86.64463026,  61.8355859 ,  88.7539719 ,  89.56805279,
        81.08331088,  92.68556353,  85.78974329,  68.17443764,
        91.49971594,  54.60156194])

In [25]:
data={
    "predicts": [74.1971025 , 100.45497612,  82.57970877,  77.81370664,
        73.55764703,  80.55819161,  62.16563158,  91.50223901,
        67.79945444,  65.81231221, 105.17845991,  64.75029233,
        72.32863245, 110.6438861 ,  68.57639939,  85.65294945,
        77.58870391, 100.66321403,  98.85070277,  60.07104508,
        86.64463026,  61.8355859 ,  88.7539719 ,  89.56805279,
        81.08331088,  92.68556353,  85.78974329,  68.17443764,
        91.49971594,  54.60156194],
    "ytest": [74.1971025 , 100.45497612,  82.57970877,  77.81370664,
        73.55764703,  80.55819161,  62.16563158,  91.50223901,
        67.79945444,  65.81231221, 105.17845991,  64.75029233,
        72.32863245, 110.6438861 ,  68.57639939,  85.65294945,
        77.58870391, 100.66321403,  98.85070277,  60.07104508,
        86.64463026,  61.8355859 ,  88.7539719 ,  89.56805279,
        81.08331088,  92.68556353,  85.78974329,  68.17443764,
        91.49971594,  54.60156194]
}
preds = pd.DataFrame(data)

print(preds)

      predicts       ytest
0    74.197102   74.197102
1   100.454976  100.454976
2    82.579709   82.579709
3    77.813707   77.813707
4    73.557647   73.557647
5    80.558192   80.558192
6    62.165632   62.165632
7    91.502239   91.502239
8    67.799454   67.799454
9    65.812312   65.812312
10  105.178460  105.178460
11   64.750292   64.750292
12   72.328632   72.328632
13  110.643886  110.643886
14   68.576399   68.576399
15   85.652949   85.652949
16   77.588704   77.588704
17  100.663214  100.663214
18   98.850703   98.850703
19   60.071045   60.071045
20   86.644630   86.644630
21   61.835586   61.835586
22   88.753972   88.753972
23   89.568053   89.568053
24   81.083311   81.083311
25   92.685564   92.685564
26   85.789743   85.789743
27   68.174438   68.174438
28   91.499716   91.499716
29   54.601562   54.601562

In [27]:
preds['ytest'] = ytest

In [42]:
ytest[6:]

126     62
127     92
128     68
129     66
130    106
131     65
132     73
133    111
134     69
135     86
136     78
137    101
138     99
139     60
140     87
141     62
142     89
143     90
144     81
145     93
146     86
147     68
148     92
149     55
Name: W, dtype: int64

In [31]:
preds

      predicts  ytest
0    74.197102    NaN
1   100.454976    NaN
2    82.579709    NaN
3    77.813707    NaN
4    73.557647    NaN
5    80.558192    NaN
6    62.165632    NaN
7    91.502239    NaN
8    67.799454    NaN
9    65.812312    NaN
10  105.178460    NaN
11   64.750292    NaN
12   72.328632    NaN
13  110.643886    NaN
14   68.576399    NaN
15   85.652949    NaN
16   77.588704    NaN
17  100.663214    NaN
18   98.850703    NaN
19   60.071045    NaN
20   86.644630    NaN
21   61.835586    NaN
22   88.753972    NaN
23   89.568053    NaN
24   81.083311    NaN
25   92.685564    NaN
26   85.789743    NaN
27   68.174438    NaN
28   91.499716    NaN
29   54.601562    NaN