In [24]:
import pandas as pd

# Specify the path to your Excel file
file_path = "Newly-constructed-apartments-by-category of-funding-source-and-by-canton.xlsx"

# Read all sheets into a dictionary of DataFrames with a single header row
dfs = pd.read_excel(file_path, sheet_name=None, header=0, skiprows=0)

# Create an empty dictionary to store cleaned DataFrames for each sheet
cleaned_dfs = {}

# Iterate through each sheet and apply the cleaning steps
for sheet_name, df in dfs.items():
    print(f"Processing sheet: {sheet_name}")
    
    # Select rows 2 through 40 using iloc (0-based indexing)
    df_subset = df.iloc[1:40, :]
    
    # Drop rows with any NaN values
    df_cleaned = df_subset.dropna(how='any')
    
    # Store the cleaned DataFrame in the dictionary
    cleaned_dfs[sheet_name] = df_cleaned
    
    print(f"Cleaned DataFrame for {sheet_name}:\n{df_cleaned.head()}\n")

Processing sheet: 2022 (new survey)
Cleaned DataFrame for 2022 (new survey):
Empty DataFrame
Columns: [Unnamed: 0, Newly constructed apartments by category of funding source and by canton. 2022, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13, Unnamed: 14, Unnamed: 15, Unnamed: 16, Unnamed: 17, Unnamed: 18, Unnamed: 19, Unnamed: 20, Unnamed: 21, Unnamed: 22, T 9.4.3.3.5, Unnamed: 24, Unnamed: 25]
Index: []

[0 rows x 26 columns]

Processing sheet: 2021 (new survey)
Cleaned DataFrame for 2021 (new survey):
Empty DataFrame
Columns: [Unnamed: 0, Newly constructed apartments by category of funding source and by canton. 2021, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13, Unnamed: 14, Unnamed: 15, Unnamed: 16, Unnamed: 17, Unnamed: 18, Unnamed: 19, Unnamed: 20, Unnamed: 21, Unnamed: 22, T 9.4.3.3.5, Unnamed: 24, Unnamed: 25]
Index: []

[0 rows x 26 columns]

Processing sheet: 2020 (new survey)
Cleaned DataFrame for 2020 (new survey):
Empty DataFrame
Columns: [Unnamed: 0, Newly constructed apartments by category of funding source and by canton. 2020, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13, Unnamed: 14, Unnamed: 15, Unnamed: 16, Unnamed: 17, Unnamed: 18, Unnamed: 19, Unnamed: 20, Unnamed: 21, Unnamed: 22, T 9.4.3.3.5, Unnamed: 24, Unnamed: 25]
Index: []

[0 rows x 26 columns]

Processing sheet: 2019 (new survey)
Cleaned DataFrame for 2019 (new survey):
Empty DataFrame
Columns: [Unnamed: 0, Newly constructed apartments by category of funding source and by canton. 2019, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13, Unnamed: 14, Unnamed: 15, Unnamed: 16, Unnamed: 17, Unnamed: 18, Unnamed: 19, Unnamed: 20, Unnamed: 21, Unnamed: 22, T 9.4.3.3.5, Unnamed: 24, Unnamed: 25]
Index: []

[0 rows x 26 columns]

Processing sheet: 2018 (new survey)
Cleaned DataFrame for 2018 (new survey):
Empty DataFrame
Columns: [Unnamed: 0, Newly constructed apartments by category of funding source and by canton. 2018, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13, Unnamed: 14, Unnamed: 15, Unnamed: 16, Unnamed: 17, Unnamed: 18, Unnamed: 19, Unnamed: 20, Unnamed: 21, Unnamed: 22, T 9.4.3.3.5, Unnamed: 24, Unnamed: 25]
Index: []

[0 rows x 26 columns]

Processing sheet: 2017 (new survey)
Cleaned DataFrame for 2017 (new survey):
Empty DataFrame
Columns: [Unnamed: 0, Newly constructed apartments by category of funding source and by canton. 2017, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13, Unnamed: 14, Unnamed: 15, Unnamed: 16, Unnamed: 17, Unnamed: 18, Unnamed: 19, Unnamed: 20, Unnamed: 21, Unnamed: 22, T 9.4.3.3.5, Unnamed: 24, Unnamed: 25]
Index: []

[0 rows x 26 columns]

Processing sheet: 2016 (new survey)
Cleaned DataFrame for 2016 (new survey):
Empty DataFrame
Columns: [Unnamed: 0, Newly constructed apartments by category of funding source and by canton. 2016, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13, Unnamed: 14, Unnamed: 15, Unnamed: 16, Unnamed: 17, Unnamed: 18, Unnamed: 19, Unnamed: 20, Unnamed: 21, Unnamed: 22, T 9.4.3.3.5, Unnamed: 24, Unnamed: 25]
Index: []

[0 rows x 26 columns]

Processing sheet: 2015 (new survey)
Cleaned DataFrame for 2015 (new survey):
Empty DataFrame
Columns: [Unnamed: 0, Newly constructed apartments by category of funding source and by canton. 2015, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13, Unnamed: 14, Unnamed: 15, Unnamed: 16, Unnamed: 17, Unnamed: 18, Unnamed: 19, Unnamed: 20, Unnamed: 21, Unnamed: 22, T 9.4.3.3.5]
Index: []

[0 rows x 24 columns]

Processing sheet: 2014 (new survey)
Cleaned DataFrame for 2014 (new survey):
Empty DataFrame
Columns: [Unnamed: 0, Newly constructed apartments by category of funding source and by canton. 2014, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13, Unnamed: 14, Unnamed: 15, Unnamed: 16, Unnamed: 17, Unnamed: 18, Unnamed: 19, Unnamed: 20, Unnamed: 21, Unnamed: 22, T 09.04.02.13]
Index: []

[0 rows x 24 columns]

Processing sheet: 2013 (new survey)
Cleaned DataFrame for 2013 (new survey):
Empty DataFrame
Columns: [Unnamed: 0, Newly constructed apartments by category of funding source and by canton. 2013, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13, Unnamed: 14, Unnamed: 15, Unnamed: 16, Unnamed: 17, Unnamed: 18, Unnamed: 19, Unnamed: 20, Unnamed: 21, Unnamed: 22, T 09.04.02.13]
Index: []

[0 rows x 24 columns]

Processing sheet: 2012 (new survey)
Cleaned DataFrame for 2012 (new survey):
Empty DataFrame
Columns: [Unnamed: 0, Newly constructed apartments by category of funding source and by canton. 2012, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13, Unnamed: 14, Unnamed: 15, Unnamed: 16, Unnamed: 17, Unnamed: 18, Unnamed: 19, Unnamed: 20, Unnamed: 21, Unnamed: 22, T 09.04.02.13]
Index: []

[0 rows x 24 columns]

Processing sheet: 2012 (old survey)
Cleaned DataFrame for 2012 (old survey):
Empty DataFrame
Columns: [Unnamed: 0, Newly constructed apartments by category of funding source and by canton. 2012, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13, Unnamed: 14, Unnamed: 15, Unnamed: 16, Unnamed: 17, Unnamed: 18, Unnamed: 19, Unnamed: 20, Unnamed: 21, Unnamed: 22, T 9.4.3.3.5]
Index: []

[0 rows x 24 columns]

Processing sheet: 2011
Cleaned DataFrame for 2011:
Empty DataFrame
Columns: [Unnamed: 0, Newly constructed apartments by category of funding source and by canton. 2011, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13, Unnamed: 14, Unnamed: 15, Unnamed: 16, Unnamed: 17, Unnamed: 18, Unnamed: 19, Unnamed: 20, Unnamed: 21, Unnamed: 22, T 9.4.3.3.5]
Index: []

[0 rows x 24 columns]

Processing sheet: 2010
Cleaned DataFrame for 2010:
Empty DataFrame
Columns: [Unnamed: 0, Newly constructed apartments by category of funding source and by canton. 2010, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13, Unnamed: 14, Unnamed: 15, Unnamed: 16, Unnamed: 17, Unnamed: 18, Unnamed: 19, Unnamed: 20, Unnamed: 21, Unnamed: 22, T 9.4.3.3.5]
Index: []

[0 rows x 24 columns]

Processing sheet: 2009
Cleaned DataFrame for 2009:
Empty DataFrame
Columns: [Unnamed: 0, Newly constructed apartments by category of funding source and by canton. 2009, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13, Unnamed: 14, Unnamed: 15, Unnamed: 16, Unnamed: 17, Unnamed: 18, Unnamed: 19, Unnamed: 20, Unnamed: 21, Unnamed: 22, T 9.4.3.3.5]
Index: []

[0 rows x 24 columns]

Processing sheet: 2008
Cleaned DataFrame for 2008:
Empty DataFrame
Columns: [Unnamed: 0, Newly constructed apartments by category of funding source and by canton. 2008, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13, Unnamed: 14, Unnamed: 15, Unnamed: 16, Unnamed: 17, Unnamed: 18, Unnamed: 19, Unnamed: 20, Unnamed: 21, Unnamed: 22, T 9.4.3.3.5]
Index: []

[0 rows x 24 columns]

Processing sheet: 2007
Cleaned DataFrame for 2007:
Empty DataFrame
Columns: [Unnamed: 0, Newly constructed apartments by category of funding source and by canton. 2007, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13, Unnamed: 14, Unnamed: 15, Unnamed: 16, Unnamed: 17, Unnamed: 18, Unnamed: 19, Unnamed: 20, Unnamed: 21, Unnamed: 22, T 9.4.3.3.5]
Index: []

[0 rows x 24 columns]

Processing sheet: 2006
Cleaned DataFrame for 2006:
   Newly constructed apartments by category of funding source and by canton. 2006  \
12                                              Total
14                                 Lake Geneva region
15                                              Waadt
16                                             Wallis
17                                             Geneva

   Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6  \
12      41989        121          0          2        119      41868
14       8022         16          0          1         15       8006
15       4240         14          0          0         14       4226
16       2621          1          0          0          1       2620
17       1161          1          0          1          0       1160

   Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 T 9.4.3.3.5
12       1764      15064       1259       25040       16733
14        331       2285        425        5390        4050
15        150       1251        250        2825        2214
16         18        474         31        2128        1611
17        163        560        144         437         225

Processing sheet: 2005
Cleaned DataFrame for 2005:
   Newly constructed apartments by category of funding source and by canton. 2005  \
12                                              Total
14                                 Lake Geneva region
15                                              Waadt
16                                             Wallis
17                                             Geneva

   Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6  \
12      37958        288          0         81        207      37670
14       7410         32          0          0         32       7378
15       3513         23          0          0         23       3490
16       2316          0          0          0          0       2316
17       1581          9          0          0          9       1572

   Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 T 9.4.3.3.5
12       1881      12207        870       23582       16233
14        491       2143        140        4744        3667
15        350       1005         87        2135        1790
16          2        406          0        1908        1530
17        139        732         53         701         347

Processing sheet: 2004
Cleaned DataFrame for 2004:
   Newly constructed apartments by category of funding source and by canton. 2004  \
12                                              Total
14                                 Lake Geneva region
15                                              Waadt
16                                             Wallis
17                                             Geneva

   Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6  \
12      36935        447          0        145        302      36488
14       7061         72          0          0         72       6989
15       3823         56          0          0         56       3767
16       1838          8          0          0          8       1830
17       1400          8          0          0          8       1392

   Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 T 9.4.3.3.5
12       1564      12486        752       22438       15603
14        553       2071         16        4365        3497
15        378       1125         10        2264        1690
16          3        247          6        1580        1372
17        172        699          0         521         435

Processing sheet: 2003
Cleaned DataFrame for 2003:
   Newly constructed apartments by category of funding source and by canton. 2003  \
12                                              Total
14                                 Lake Geneva region
15                                              Waadt
16                                             Wallis
17                                             Geneva

   Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6  \
12      32096        310          1        118        191      31786
14       5383        138          0         68         70       5245
15       2607         13          0          0         13       2594
16       1570         18          0          0         18       1552
17       1206        107          0         68         39       1099

   Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 T 9.4.3.3.5
12        968      11086        837       19732       14131
14         84       1815         43        3346        2931
15         69        788         29        1737        1520
16          3        280         14        1269        1121
17         12        747          0         340         290

Processing sheet: 2002
Cleaned DataFrame for 2002:
   Newly constructed apartments by category of funding source and by canton. 2002  \
13                                              Total
15                                 Lake Geneva region
16                                              Waadt
17                                             Wallis
18                                             Geneva

   Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6  \
13      28644        216          6         11        199      28428
15       4681         17          6          5          6       4664
16       2119         15          6          5          4       2104
17       1250          0          0          0          0       1250
18       1312          2          0          0          2       1310

   Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 T 9.4.3.3.5
13       1044      10226        897       17158       12555
15        197       1713         43        2754        2518
16         80        682         43        1342        1214
17         30        113          0        1107        1020
18         87        918          0         305         284

Processing sheet: 2001
Cleaned DataFrame for 2001:
   Newly constructed apartments by category of funding source and by canton. 2001  \
13                                              Total
15                                 Lake Geneva region
16                                              Waadt
17                                             Wallis
18                                             Geneva

   Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6  \
13      28873        505          0         25        480      28368
15       5170        153          0          0        153       5017
16       2210         20          0          0         20       2190
17       1400          1          0          0          1       1399
18       1560        132          0          0        132       1428

   Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 T 9.4.3.3.5
13       1009       9928        772       13051        4380
15         56       1848         50        2713         400
16         36        693         27        1341         120
17         13        212         23        1059         115
18          7        943          0         313         165

Processing sheet: 2000
Cleaned DataFrame for 2000:
   Newly constructed apartments by category of funding source and by canton. 2000  \
13                                              Total
15                                 Lake Geneva region
16                                              Waadt
17                                             Wallis
18                                             Geneva

   Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6  \
13      32214        430        119         87        224      31784
15       5506        247        113         85         49       5259
16       2199        214        113         53         48       1985
17       1320          0          0          0          0       1320
18       1987         33          0         32          1       1954

   Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 T 9.4.3.3.5
13       1622      10695        646       19467       14868
15        149       1851         59        3259        2734
16         86        441         31        1458        1301
17          1        162         28        1157        1080
18         62       1248          0         644         353

Processing sheet: 1999
Cleaned DataFrame for 1999:
   Newly constructed apartments by category of funding source and by canton. 1999  \
13                                              Total
15                                 Lake Geneva region
16                                              Waadt
17                                             Wallis
18                                             Geneva

   Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6  \
13      33108        427          6        151        270      32681
15       5091        217          5        130         82       4874
16       1706          5          0          0          5       1701
17       1524          6          5          0          1       1518
18       1861        206          0        130         76       1655

   Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 T 9.4.3.3.5
13       1236      11041        745       20404       15122
15         39       1720         29        3115        2510
16         39        397         12        1265        1055
17          0        288         17        1230        1101
18          0       1035          0         620         354

Processing sheet: 1998
Cleaned DataFrame for 1998:
   Newly constructed apartments by category of funding source and by canton. 1998  \
13                                              Total
15                                 Lake Geneva region
16                                              Waadt
17                                             Wallis
18                                             Geneva

   Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6  \
13      33734        569          8        168        393      33165
15       5156        284          5        108        171       4872
16       2250         84          0         52         32       2166
17       1405          5          5          0          0       1400
18       1501        195          0         56        139       1306

   Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 T 9.4.3.3.5
13       1854      12121       1057       14497        4693
15        360       1913         62        2241         358
16        281        781         62         918         186
17         79        230          0        1040          51
18          0        902          0         283         121

In [25]:
cleaned_dfs['2019 (new survey)']

Empty DataFrame
Columns: [Unnamed: 0, Newly constructed apartments by category of funding source and by canton. 2019, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13, Unnamed: 14, Unnamed: 15, Unnamed: 16, Unnamed: 17, Unnamed: 18, Unnamed: 19, Unnamed: 20, Unnamed: 21, Unnamed: 22, T 9.4.3.3.5, Unnamed: 24, Unnamed: 25]
Index: []

[0 rows x 26 columns]

In [1]:
import pandas as pd

# Specify the path to your Excel file
file_path = "Newly-constructed-apartments-by-category of-funding-source-and-by-canton.xlsx"

# Read the Excel file
# This reads all sheets into a dictionary with sheet names as keys and DataFrames as values
xlsx = pd.read_excel(file_path, sheet_name=None, skiprows=2)

# Check which sheets are present in the file
sheet_names = xlsx.keys()
print(f"Sheets found: {sheet_names}")

Sheets found: dict_keys(['2022 (new survey)', '2021 (new survey)', '2020 (new survey)', '2019 (new survey)', '2018 (new survey)', '2017 (new survey)', '2016 (new survey)', '2015 (new survey)', '2014 (new survey)', '2013 (new survey)', '2012 (new survey)', '2012 (old survey)', '2011', '2010', '2009', '2008', '2007', '2006', '2005', '2004', '2003', '2002', '2001', '2000', '1999', '1998'])

In [2]:
import pandas as pd

# Specify the path to your Excel file
file_path = "Newly-constructed-apartments-by-category of-funding-source-and-by-canton.xlsx"

# Read all sheets into a dictionary of DataFrames
dfs = pd.read_excel(file_path, sheet_name=None, header=[3, 4, 5], skiprows=6)

# Create an empty dictionary to store cleaned DataFrames for each sheet
cleaned_dfs = {}

# Iterate through each sheet and apply the cleaning steps
for sheet_name, df in dfs.items():
    # Print the current sheet being processed
    print(f"Processing sheet: {sheet_name}")

    # Select rows 2 through 40 using iloc
    df_subset = df.iloc[1:40, :]

    # Drop rows with any NaN values
    df_cleaned = df_subset.dropna(how='any')

    # Store the cleaned DataFrame in the dictionary
    cleaned_dfs[sheet_name] = df_cleaned

    # Optional: Display the cleaned DataFrame for verification
    print(f"Cleaned DataFrame for {sheet_name}:\n{df_cleaned.head()}\n")

# At this point, `cleaned_dfs` is a dictionary containing the cleaned DataFrames for each sheet

Processing sheet: 2022 (new survey)
Cleaned DataFrame for 2022 (new survey):
Empty DataFrame
Columns: [(Unnamed: 0_level_0, Unnamed: 0_level_1, Unnamed: 0_level_2), (Unnamed: 1_level_0, Unnamed: 1_level_1, Unnamed: 1_level_2), (Unnamed: 2_level_0, Unnamed: 2_level_1, Unnamed: 2_level_2), (Unnamed: 3_level_0, Unnamed: 3_level_1, Unnamed: 3_level_2), (Unnamed: 4_level_0, Unnamed: 4_level_1, Unnamed: 4_level_2), (Unnamed: 5_level_0, Unnamed: 5_level_1, Unnamed: 5_level_2), (Unnamed: 6_level_0, Unnamed: 6_level_1, Unnamed: 6_level_2), (Confed-, eration, Unnamed: 7_level_2), (Confed-, eration, Unnamed: 8_level_2), (Cantons, Unnamed: 9_level_1, Unnamed: 9_level_2), (Cantons, Unnamed: 10_level_1, Unnamed: 10_level_2), (Munic-, ipalities, Unnamed: 11_level_2), (Munic-, ipalities, Unnamed: 12_level_2), (Munic-, ipalities, Unnamed: 13_level_2), (Munic-, ipalities, Unnamed: 14_level_2), (Munic-, ipalities, Unnamed: 15_level_2), (Munic-, ipalities, Unnamed: 16_level_2), (Total, Unnamed: 17_level_1, Unnamed: 17_level_2), (Total, Unnamed: 18_level_1, Unnamed: 18_level_2), (of which building, cooperatives, Unnamed: 19_level_2), (of which building, cooperatives, Unnamed: 20_level_2), (of which building, cooperatives, Unnamed: 21_level_2), (of which building, cooperatives, Unnamed: 22_level_2), (of which building, cooperatives, Unnamed: 23_level_2), (of which building, cooperatives, Unnamed: 24_level_2), (of which building, cooperatives, Unnamed: 25_level_2)]
Index: []

[0 rows x 26 columns]

Processing sheet: 2021 (new survey)
Cleaned DataFrame for 2021 (new survey):
Empty DataFrame
Columns: [(Unnamed: 0_level_0, Unnamed: 0_level_1, Unnamed: 0_level_2), (Unnamed: 1_level_0, Unnamed: 1_level_1, Unnamed: 1_level_2), (Unnamed: 2_level_0, Unnamed: 2_level_1, Unnamed: 2_level_2), (Unnamed: 3_level_0, Unnamed: 3_level_1, Unnamed: 3_level_2), (Unnamed: 4_level_0, Unnamed: 4_level_1, Unnamed: 4_level_2), (Unnamed: 5_level_0, Unnamed: 5_level_1, Unnamed: 5_level_2), (Unnamed: 6_level_0, Unnamed: 6_level_1, Unnamed: 6_level_2), (Confed-, eration, Unnamed: 7_level_2), (Confed-, eration, Unnamed: 8_level_2), (Cantons, Unnamed: 9_level_1, Unnamed: 9_level_2), (Cantons, Unnamed: 10_level_1, Unnamed: 10_level_2), (Munic-, ipalities, Unnamed: 11_level_2), (Munic-, ipalities, Unnamed: 12_level_2), (Munic-, ipalities, Unnamed: 13_level_2), (Munic-, ipalities, Unnamed: 14_level_2), (Munic-, ipalities, Unnamed: 15_level_2), (Munic-, ipalities, Unnamed: 16_level_2), (Total, Unnamed: 17_level_1, Unnamed: 17_level_2), (Total, Unnamed: 18_level_1, Unnamed: 18_level_2), (of which building, cooperatives, Unnamed: 19_level_2), (of which building, cooperatives, Unnamed: 20_level_2), (of which building, cooperatives, Unnamed: 21_level_2), (of which building, cooperatives, Unnamed: 22_level_2), (of which building, cooperatives, Unnamed: 23_level_2), (of which building, cooperatives, Unnamed: 24_level_2), (of which building, cooperatives, Unnamed: 25_level_2)]
Index: []

[0 rows x 26 columns]

Processing sheet: 2020 (new survey)
Cleaned DataFrame for 2020 (new survey):
Empty DataFrame
Columns: [(Unnamed: 0_level_0, Unnamed: 0_level_1, Unnamed: 0_level_2), (Unnamed: 1_level_0, Unnamed: 1_level_1, Unnamed: 1_level_2), (Unnamed: 2_level_0, Unnamed: 2_level_1, Unnamed: 2_level_2), (Unnamed: 3_level_0, Unnamed: 3_level_1, Unnamed: 3_level_2), (Unnamed: 4_level_0, Unnamed: 4_level_1, Unnamed: 4_level_2), (Unnamed: 5_level_0, Unnamed: 5_level_1, Unnamed: 5_level_2), (Unnamed: 6_level_0, Unnamed: 6_level_1, Unnamed: 6_level_2), (Confed-, eration, Unnamed: 7_level_2), (Confed-, eration, Unnamed: 8_level_2), (Cantons, Unnamed: 9_level_1, Unnamed: 9_level_2), (Cantons, Unnamed: 10_level_1, Unnamed: 10_level_2), (Munic-, ipalities, Unnamed: 11_level_2), (Munic-, ipalities, Unnamed: 12_level_2), (Munic-, ipalities, Unnamed: 13_level_2), (Munic-, ipalities, Unnamed: 14_level_2), (Munic-, ipalities, Unnamed: 15_level_2), (Munic-, ipalities, Unnamed: 16_level_2), (Total, Unnamed: 17_level_1, Unnamed: 17_level_2), (Total, Unnamed: 18_level_1, Unnamed: 18_level_2), (of which building, cooperatives, Unnamed: 19_level_2), (of which building, cooperatives, Unnamed: 20_level_2), (of which building, cooperatives, Unnamed: 21_level_2), (of which building, cooperatives, Unnamed: 22_level_2), (of which building, cooperatives, Unnamed: 23_level_2), (of which building, cooperatives, Unnamed: 24_level_2), (of which building, cooperatives, Unnamed: 25_level_2)]
Index: []

[0 rows x 26 columns]

Processing sheet: 2019 (new survey)
Cleaned DataFrame for 2019 (new survey):
Empty DataFrame
Columns: [(Unnamed: 0_level_0, Unnamed: 0_level_1, Unnamed: 0_level_2), (Unnamed: 1_level_0, Unnamed: 1_level_1, Unnamed: 1_level_2), (Unnamed: 2_level_0, Unnamed: 2_level_1, Unnamed: 2_level_2), (Unnamed: 3_level_0, Unnamed: 3_level_1, Unnamed: 3_level_2), (Unnamed: 4_level_0, Unnamed: 4_level_1, Unnamed: 4_level_2), (Unnamed: 5_level_0, Unnamed: 5_level_1, Unnamed: 5_level_2), (Unnamed: 6_level_0, Unnamed: 6_level_1, Unnamed: 6_level_2), (Confed-, eration, Unnamed: 7_level_2), (Confed-, eration, Unnamed: 8_level_2), (Cantons, Unnamed: 9_level_1, Unnamed: 9_level_2), (Cantons, Unnamed: 10_level_1, Unnamed: 10_level_2), (Munic-, ipalities, Unnamed: 11_level_2), (Munic-, ipalities, Unnamed: 12_level_2), (Munic-, ipalities, Unnamed: 13_level_2), (Munic-, ipalities, Unnamed: 14_level_2), (Munic-, ipalities, Unnamed: 15_level_2), (Munic-, ipalities, Unnamed: 16_level_2), (Total, Unnamed: 17_level_1, Unnamed: 17_level_2), (Total, Unnamed: 18_level_1, Unnamed: 18_level_2), (of which building, cooperatives, Unnamed: 19_level_2), (of which building, cooperatives, Unnamed: 20_level_2), (of which building, cooperatives, Unnamed: 21_level_2), (of which building, cooperatives, Unnamed: 22_level_2), (of which building, cooperatives, Unnamed: 23_level_2), (of which building, cooperatives, Unnamed: 24_level_2), (of which building, cooperatives, Unnamed: 25_level_2)]
Index: []

[0 rows x 26 columns]

Processing sheet: 2018 (new survey)
Cleaned DataFrame for 2018 (new survey):
Empty DataFrame
Columns: [(Unnamed: 0_level_0, Unnamed: 0_level_1, Unnamed: 0_level_2), (Unnamed: 1_level_0, Unnamed: 1_level_1, Unnamed: 1_level_2), (Unnamed: 2_level_0, Unnamed: 2_level_1, Unnamed: 2_level_2), (Unnamed: 3_level_0, Unnamed: 3_level_1, Unnamed: 3_level_2), (Unnamed: 4_level_0, Unnamed: 4_level_1, Unnamed: 4_level_2), (Unnamed: 5_level_0, Unnamed: 5_level_1, Unnamed: 5_level_2), (Unnamed: 6_level_0, Unnamed: 6_level_1, Unnamed: 6_level_2), (Confed-, eration, Unnamed: 7_level_2), (Confed-, eration, Unnamed: 8_level_2), (Cantons, Unnamed: 9_level_1, Unnamed: 9_level_2), (Cantons, Unnamed: 10_level_1, Unnamed: 10_level_2), (Munic-, ipalities, Unnamed: 11_level_2), (Munic-, ipalities, Unnamed: 12_level_2), (Munic-, ipalities, Unnamed: 13_level_2), (Munic-, ipalities, Unnamed: 14_level_2), (Munic-, ipalities, Unnamed: 15_level_2), (Munic-, ipalities, Unnamed: 16_level_2), (Total, Unnamed: 17_level_1, Unnamed: 17_level_2), (Total, Unnamed: 18_level_1, Unnamed: 18_level_2), (of which building, cooperatives, Unnamed: 19_level_2), (of which building, cooperatives, Unnamed: 20_level_2), (of which building, cooperatives, Unnamed: 21_level_2), (of which building, cooperatives, Unnamed: 22_level_2), (of which building, cooperatives, Unnamed: 23_level_2), (of which building, cooperatives, Unnamed: 24_level_2), (of which building, cooperatives, Unnamed: 25_level_2)]
Index: []

[0 rows x 26 columns]

Processing sheet: 2017 (new survey)
Cleaned DataFrame for 2017 (new survey):
Empty DataFrame
Columns: [(Unnamed: 0_level_0, Unnamed: 0_level_1, Unnamed: 0_level_2), (Unnamed: 1_level_0, Unnamed: 1_level_1, Unnamed: 1_level_2), (Unnamed: 2_level_0, Unnamed: 2_level_1, Unnamed: 2_level_2), (Unnamed: 3_level_0, Unnamed: 3_level_1, Unnamed: 3_level_2), (Unnamed: 4_level_0, Unnamed: 4_level_1, Unnamed: 4_level_2), (Unnamed: 5_level_0, Unnamed: 5_level_1, Unnamed: 5_level_2), (Unnamed: 6_level_0, Unnamed: 6_level_1, Unnamed: 6_level_2), (Confed-, eration, Unnamed: 7_level_2), (Confed-, eration, Unnamed: 8_level_2), (Cantons, Unnamed: 9_level_1, Unnamed: 9_level_2), (Cantons, Unnamed: 10_level_1, Unnamed: 10_level_2), (Munic-, ipalities, Unnamed: 11_level_2), (Munic-, ipalities, Unnamed: 12_level_2), (Munic-, ipalities, Unnamed: 13_level_2), (Munic-, ipalities, Unnamed: 14_level_2), (Munic-, ipalities, Unnamed: 15_level_2), (Munic-, ipalities, Unnamed: 16_level_2), (Total, Unnamed: 17_level_1, Unnamed: 17_level_2), (Total, Unnamed: 18_level_1, Unnamed: 18_level_2), (of which building, cooperatives, Unnamed: 19_level_2), (of which building, cooperatives, Unnamed: 20_level_2), (of which building, cooperatives, Unnamed: 21_level_2), (of which building, cooperatives, Unnamed: 22_level_2), (of which building, cooperatives, Unnamed: 23_level_2), (of which building, cooperatives, Unnamed: 24_level_2), (of which building, cooperatives, Unnamed: 25_level_2)]
Index: []

[0 rows x 26 columns]

Processing sheet: 2016 (new survey)
Cleaned DataFrame for 2016 (new survey):
Empty DataFrame
Columns: [(Unnamed: 0_level_0, Unnamed: 0_level_1, Unnamed: 0_level_2), (Unnamed: 1_level_0, Unnamed: 1_level_1, Unnamed: 1_level_2), (Unnamed: 2_level_0, Unnamed: 2_level_1, Unnamed: 2_level_2), (Unnamed: 3_level_0, Unnamed: 3_level_1, Unnamed: 3_level_2), (Unnamed: 4_level_0, Unnamed: 4_level_1, Unnamed: 4_level_2), (Unnamed: 5_level_0, Unnamed: 5_level_1, Unnamed: 5_level_2), (Unnamed: 6_level_0, Unnamed: 6_level_1, Unnamed: 6_level_2), (Confed-, eration, Unnamed: 7_level_2), (Confed-, eration, Unnamed: 8_level_2), (Cantons, Unnamed: 9_level_1, Unnamed: 9_level_2), (Cantons, Unnamed: 10_level_1, Unnamed: 10_level_2), (Munic-, ipalities, Unnamed: 11_level_2), (Munic-, ipalities, Unnamed: 12_level_2), (Munic-, ipalities, Unnamed: 13_level_2), (Munic-, ipalities, Unnamed: 14_level_2), (Munic-, ipalities, Unnamed: 15_level_2), (Munic-, ipalities, Unnamed: 16_level_2), (Total, Unnamed: 17_level_1, Unnamed: 17_level_2), (Total, Unnamed: 18_level_1, Unnamed: 18_level_2), (of which building, cooperatives, Unnamed: 19_level_2), (of which building, cooperatives, Unnamed: 20_level_2), (Total, Unnamed: 21_level_1, Unnamed: 21_level_2), (Total, Unnamed: 22_level_1, Unnamed: 22_level_2), (of which private, individuals, Unnamed: 23_level_2), (of which private, individuals, Unnamed: 24_level_2), (of which private, individuals, Unnamed: 25_level_2)]
Index: []

[0 rows x 26 columns]

Processing sheet: 2015 (new survey)
Cleaned DataFrame for 2015 (new survey):
Empty DataFrame
Columns: [(Unnamed: 0_level_0, Unnamed: 0_level_1, Unnamed: 0_level_2), (Unnamed: 1_level_0, Unnamed: 1_level_1, Unnamed: 1_level_2), (Unnamed: 2_level_0, Unnamed: 2_level_1, Unnamed: 2_level_2), (Unnamed: 3_level_0, Unnamed: 3_level_1, Unnamed: 3_level_2), (Unnamed: 4_level_0, Unnamed: 4_level_1, Unnamed: 4_level_2), (Unnamed: 5_level_0, Unnamed: 5_level_1, Unnamed: 5_level_2), (Unnamed: 6_level_0, Unnamed: 6_level_1, Unnamed: 6_level_2), (Confed-, eration, Unnamed: 7_level_2), (Confed-, eration, Unnamed: 8_level_2), (Cantons, Unnamed: 9_level_1, Unnamed: 9_level_2), (Cantons, Unnamed: 10_level_1, Unnamed: 10_level_2), (Munic-, ipalities, Unnamed: 11_level_2), (Munic-, ipalities, Unnamed: 12_level_2), (Munic-, ipalities, Unnamed: 13_level_2), (Munic-, ipalities, Unnamed: 14_level_2), (Munic-, ipalities, Unnamed: 15_level_2), (Munic-, ipalities, Unnamed: 16_level_2), (Total, Unnamed: 17_level_1, Unnamed: 17_level_2), (Total, Unnamed: 18_level_1, Unnamed: 18_level_2), (of which building, cooperatives, Unnamed: 19_level_2), (of which building, cooperatives, Unnamed: 20_level_2), (Total, Unnamed: 21_level_1, Unnamed: 21_level_2), (Total, Unnamed: 22_level_1, Unnamed: 22_level_2), (of which private, individuals, Unnamed: 23_level_2)]
Index: []

[0 rows x 24 columns]

Processing sheet: 2014 (new survey)
Cleaned DataFrame for 2014 (new survey):
Empty DataFrame
Columns: [(Unnamed: 0_level_0, Unnamed: 0_level_1, Unnamed: 0_level_2), (Unnamed: 1_level_0, Unnamed: 1_level_1, Unnamed: 1_level_2), (Unnamed: 2_level_0, Unnamed: 2_level_1, Unnamed: 2_level_2), (Unnamed: 3_level_0, Unnamed: 3_level_1, Unnamed: 3_level_2), (Unnamed: 4_level_0, Unnamed: 4_level_1, Unnamed: 4_level_2), (Unnamed: 5_level_0, Unnamed: 5_level_1, Unnamed: 5_level_2), (Unnamed: 6_level_0, Unnamed: 6_level_1, Unnamed: 6_level_2), (Confed-, eration, Unnamed: 7_level_2), (Confed-, eration, Unnamed: 8_level_2), (Cantons, Unnamed: 9_level_1, Unnamed: 9_level_2), (Cantons, Unnamed: 10_level_1, Unnamed: 10_level_2), (Munic-, ipalities, Unnamed: 11_level_2), (Munic-, ipalities, Unnamed: 12_level_2), (Munic-, ipalities, Unnamed: 13_level_2), (Munic-, ipalities, Unnamed: 14_level_2), (Munic-, ipalities, Unnamed: 15_level_2), (Munic-, ipalities, Unnamed: 16_level_2), (Total, Unnamed: 17_level_1, Unnamed: 17_level_2), (Total, Unnamed: 18_level_1, Unnamed: 18_level_2), (of which building, cooperatives, Unnamed: 19_level_2), (of which building, cooperatives, Unnamed: 20_level_2), (Total, Unnamed: 21_level_1, Unnamed: 21_level_2), (Total, Unnamed: 22_level_1, Unnamed: 22_level_2), (of which private, individuals, Unnamed: 23_level_2)]
Index: []

[0 rows x 24 columns]

Processing sheet: 2013 (new survey)
Cleaned DataFrame for 2013 (new survey):
Empty DataFrame
Columns: [(Unnamed: 0_level_0, Unnamed: 0_level_1, Unnamed: 0_level_2), (Unnamed: 1_level_0, Unnamed: 1_level_1, Unnamed: 1_level_2), (Unnamed: 2_level_0, Unnamed: 2_level_1, Unnamed: 2_level_2), (Unnamed: 3_level_0, Unnamed: 3_level_1, Unnamed: 3_level_2), (Unnamed: 4_level_0, Unnamed: 4_level_1, Unnamed: 4_level_2), (Unnamed: 5_level_0, Unnamed: 5_level_1, Unnamed: 5_level_2), (Unnamed: 6_level_0, Unnamed: 6_level_1, Unnamed: 6_level_2), (Confed-, eration, Unnamed: 7_level_2), (Confed-, eration, Unnamed: 8_level_2), (Cantons, Unnamed: 9_level_1, Unnamed: 9_level_2), (Cantons, Unnamed: 10_level_1, Unnamed: 10_level_2), (Munic-, ipalities, Unnamed: 11_level_2), (Munic-, ipalities, Unnamed: 12_level_2), (Munic-, ipalities, Unnamed: 13_level_2), (Munic-, ipalities, Unnamed: 14_level_2), (Munic-, ipalities, Unnamed: 15_level_2), (Munic-, ipalities, Unnamed: 16_level_2), (Total, Unnamed: 17_level_1, Unnamed: 17_level_2), (Total, Unnamed: 18_level_1, Unnamed: 18_level_2), (of which building, cooperatives, Unnamed: 19_level_2), (of which building, cooperatives, Unnamed: 20_level_2), (Total, Unnamed: 21_level_1, Unnamed: 21_level_2), (Total, Unnamed: 22_level_1, Unnamed: 22_level_2), (of which private, individuals, Unnamed: 23_level_2)]
Index: []

[0 rows x 24 columns]

Processing sheet: 2012 (new survey)
Cleaned DataFrame for 2012 (new survey):
Empty DataFrame
Columns: [(Unnamed: 0_level_0, Unnamed: 0_level_1, Unnamed: 0_level_2), (Unnamed: 1_level_0, Unnamed: 1_level_1, Unnamed: 1_level_2), (Unnamed: 2_level_0, Unnamed: 2_level_1, Unnamed: 2_level_2), (Unnamed: 3_level_0, Unnamed: 3_level_1, Unnamed: 3_level_2), (Unnamed: 4_level_0, Unnamed: 4_level_1, Unnamed: 4_level_2), (Unnamed: 5_level_0, Unnamed: 5_level_1, Unnamed: 5_level_2), (Unnamed: 6_level_0, Unnamed: 6_level_1, Unnamed: 6_level_2), (Confed-, eration, Unnamed: 7_level_2), (Confed-, eration, Unnamed: 8_level_2), (Cantons, Unnamed: 9_level_1, Unnamed: 9_level_2), (Cantons, Unnamed: 10_level_1, Unnamed: 10_level_2), (Munic-, ipalities, Unnamed: 11_level_2), (Munic-, ipalities, Unnamed: 12_level_2), (Munic-, ipalities, Unnamed: 13_level_2), (Munic-, ipalities, Unnamed: 14_level_2), (Munic-, ipalities, Unnamed: 15_level_2), (Munic-, ipalities, Unnamed: 16_level_2), (Total, Unnamed: 17_level_1, Unnamed: 17_level_2), (Total, Unnamed: 18_level_1, Unnamed: 18_level_2), (of which building, cooperatives, Unnamed: 19_level_2), (of which building, cooperatives, Unnamed: 20_level_2), (Total, Unnamed: 21_level_1, Unnamed: 21_level_2), (Total, Unnamed: 22_level_1, Unnamed: 22_level_2), (of which private, individuals, Unnamed: 23_level_2)]
Index: []

[0 rows x 24 columns]

Processing sheet: 2012 (old survey)
Cleaned DataFrame for 2012 (old survey):
Empty DataFrame
Columns: [(Unnamed: 0_level_0, Unnamed: 0_level_1, Unnamed: 0_level_2), (Unnamed: 1_level_0, Unnamed: 1_level_1, Unnamed: 1_level_2), (Unnamed: 2_level_0, Unnamed: 2_level_1, Unnamed: 2_level_2), (Unnamed: 3_level_0, Unnamed: 3_level_1, Unnamed: 3_level_2), (Unnamed: 4_level_0, Unnamed: 4_level_1, Unnamed: 4_level_2), (Unnamed: 5_level_0, Unnamed: 5_level_1, Unnamed: 5_level_2), (Unnamed: 6_level_0, Unnamed: 6_level_1, Unnamed: 6_level_2), (Confed-, eration, Unnamed: 7_level_2), (Confed-, eration, Unnamed: 8_level_2), (Cantons, Unnamed: 9_level_1, Unnamed: 9_level_2), (Cantons, Unnamed: 10_level_1, Unnamed: 10_level_2), (Munic-, ipalities, Unnamed: 11_level_2), (Munic-, ipalities, Unnamed: 12_level_2), (Munic-, ipalities, Unnamed: 13_level_2), (Munic-, ipalities, Unnamed: 14_level_2), (Munic-, ipalities, Unnamed: 15_level_2), (Munic-, ipalities, Unnamed: 16_level_2), (Total, Unnamed: 17_level_1, Unnamed: 17_level_2), (Total, Unnamed: 18_level_1, Unnamed: 18_level_2), (of which building, cooperatives, Unnamed: 19_level_2), (of which building, cooperatives, Unnamed: 20_level_2), (Total, Unnamed: 21_level_1, Unnamed: 21_level_2), (Total, Unnamed: 22_level_1, Unnamed: 22_level_2), (of which private, individuals, Unnamed: 23_level_2)]
Index: []

[0 rows x 24 columns]

Processing sheet: 2011
Cleaned DataFrame for 2011:
Empty DataFrame
Columns: [(Unnamed: 0_level_0, Unnamed: 0_level_1, Unnamed: 0_level_2), (Unnamed: 1_level_0, Unnamed: 1_level_1, Unnamed: 1_level_2), (Unnamed: 2_level_0, Unnamed: 2_level_1, Unnamed: 2_level_2), (Unnamed: 3_level_0, Unnamed: 3_level_1, Unnamed: 3_level_2), (Unnamed: 4_level_0, Unnamed: 4_level_1, Unnamed: 4_level_2), (Unnamed: 5_level_0, Unnamed: 5_level_1, Unnamed: 5_level_2), (Unnamed: 6_level_0, Unnamed: 6_level_1, Unnamed: 6_level_2), (Confed-, eration, Unnamed: 7_level_2), (Confed-, eration, Unnamed: 8_level_2), (Cantons, Unnamed: 9_level_1, Unnamed: 9_level_2), (Cantons, Unnamed: 10_level_1, Unnamed: 10_level_2), (Munic-, ipalities, Unnamed: 11_level_2), (Munic-, ipalities, Unnamed: 12_level_2), (Munic-, ipalities, Unnamed: 13_level_2), (Munic-, ipalities, Unnamed: 14_level_2), (Munic-, ipalities, Unnamed: 15_level_2), (Munic-, ipalities, Unnamed: 16_level_2), (Total, Unnamed: 17_level_1, Unnamed: 17_level_2), (Total, Unnamed: 18_level_1, Unnamed: 18_level_2), (of which building, cooperatives, Unnamed: 19_level_2), (of which building, cooperatives, Unnamed: 20_level_2), (Total, Unnamed: 21_level_1, Unnamed: 21_level_2), (Total, Unnamed: 22_level_1, Unnamed: 22_level_2), (of which private, individuals, Unnamed: 23_level_2)]
Index: []

[0 rows x 24 columns]

Processing sheet: 2010
Cleaned DataFrame for 2010:
Empty DataFrame

In [3]:
df22=cleaned_dfs['2022 (new survey)']

In [4]:
df17=cleaned_dfs['2017 (new survey)']

In [5]:
df17

Empty DataFrame
Columns: [(Unnamed: 0_level_0, Unnamed: 0_level_1, Unnamed: 0_level_2), (Unnamed: 1_level_0, Unnamed: 1_level_1, Unnamed: 1_level_2), (Unnamed: 2_level_0, Unnamed: 2_level_1, Unnamed: 2_level_2), (Unnamed: 3_level_0, Unnamed: 3_level_1, Unnamed: 3_level_2), (Unnamed: 4_level_0, Unnamed: 4_level_1, Unnamed: 4_level_2), (Unnamed: 5_level_0, Unnamed: 5_level_1, Unnamed: 5_level_2), (Unnamed: 6_level_0, Unnamed: 6_level_1, Unnamed: 6_level_2), (Confed-, eration, Unnamed: 7_level_2), (Confed-, eration, Unnamed: 8_level_2), (Cantons, Unnamed: 9_level_1, Unnamed: 9_level_2), (Cantons, Unnamed: 10_level_1, Unnamed: 10_level_2), (Munic-, ipalities, Unnamed: 11_level_2), (Munic-, ipalities, Unnamed: 12_level_2), (Munic-, ipalities, Unnamed: 13_level_2), (Munic-, ipalities, Unnamed: 14_level_2), (Munic-, ipalities, Unnamed: 15_level_2), (Munic-, ipalities, Unnamed: 16_level_2), (Total, Unnamed: 17_level_1, Unnamed: 17_level_2), (Total, Unnamed: 18_level_1, Unnamed: 18_level_2), (of which building, cooperatives, Unnamed: 19_level_2), (of which building, cooperatives, Unnamed: 20_level_2), (of which building, cooperatives, Unnamed: 21_level_2), (of which building, cooperatives, Unnamed: 22_level_2), (of which building, cooperatives, Unnamed: 23_level_2), (of which building, cooperatives, Unnamed: 24_level_2), (of which building, cooperatives, Unnamed: 25_level_2)]
Index: []

[0 rows x 26 columns]

In [6]:
df22

Empty DataFrame
Columns: [(Unnamed: 0_level_0, Unnamed: 0_level_1, Unnamed: 0_level_2), (Unnamed: 1_level_0, Unnamed: 1_level_1, Unnamed: 1_level_2), (Unnamed: 2_level_0, Unnamed: 2_level_1, Unnamed: 2_level_2), (Unnamed: 3_level_0, Unnamed: 3_level_1, Unnamed: 3_level_2), (Unnamed: 4_level_0, Unnamed: 4_level_1, Unnamed: 4_level_2), (Unnamed: 5_level_0, Unnamed: 5_level_1, Unnamed: 5_level_2), (Unnamed: 6_level_0, Unnamed: 6_level_1, Unnamed: 6_level_2), (Confed-, eration, Unnamed: 7_level_2), (Confed-, eration, Unnamed: 8_level_2), (Cantons, Unnamed: 9_level_1, Unnamed: 9_level_2), (Cantons, Unnamed: 10_level_1, Unnamed: 10_level_2), (Munic-, ipalities, Unnamed: 11_level_2), (Munic-, ipalities, Unnamed: 12_level_2), (Munic-, ipalities, Unnamed: 13_level_2), (Munic-, ipalities, Unnamed: 14_level_2), (Munic-, ipalities, Unnamed: 15_level_2), (Munic-, ipalities, Unnamed: 16_level_2), (Total, Unnamed: 17_level_1, Unnamed: 17_level_2), (Total, Unnamed: 18_level_1, Unnamed: 18_level_2), (of which building, cooperatives, Unnamed: 19_level_2), (of which building, cooperatives, Unnamed: 20_level_2), (of which building, cooperatives, Unnamed: 21_level_2), (of which building, cooperatives, Unnamed: 22_level_2), (of which building, cooperatives, Unnamed: 23_level_2), (of which building, cooperatives, Unnamed: 24_level_2), (of which building, cooperatives, Unnamed: 25_level_2)]
Index: []

[0 rows x 26 columns]

In [7]:
df11=cleaned_dfs['2011']

In [8]:
df11

Empty DataFrame
Columns: [(Unnamed: 0_level_0, Unnamed: 0_level_1, Unnamed: 0_level_2), (Unnamed: 1_level_0, Unnamed: 1_level_1, Unnamed: 1_level_2), (Unnamed: 2_level_0, Unnamed: 2_level_1, Unnamed: 2_level_2), (Unnamed: 3_level_0, Unnamed: 3_level_1, Unnamed: 3_level_2), (Unnamed: 4_level_0, Unnamed: 4_level_1, Unnamed: 4_level_2), (Unnamed: 5_level_0, Unnamed: 5_level_1, Unnamed: 5_level_2), (Unnamed: 6_level_0, Unnamed: 6_level_1, Unnamed: 6_level_2), (Confed-, eration, Unnamed: 7_level_2), (Confed-, eration, Unnamed: 8_level_2), (Cantons, Unnamed: 9_level_1, Unnamed: 9_level_2), (Cantons, Unnamed: 10_level_1, Unnamed: 10_level_2), (Munic-, ipalities, Unnamed: 11_level_2), (Munic-, ipalities, Unnamed: 12_level_2), (Munic-, ipalities, Unnamed: 13_level_2), (Munic-, ipalities, Unnamed: 14_level_2), (Munic-, ipalities, Unnamed: 15_level_2), (Munic-, ipalities, Unnamed: 16_level_2), (Total, Unnamed: 17_level_1, Unnamed: 17_level_2), (Total, Unnamed: 18_level_1, Unnamed: 18_level_2), (of which building, cooperatives, Unnamed: 19_level_2), (of which building, cooperatives, Unnamed: 20_level_2), (Total, Unnamed: 21_level_1, Unnamed: 21_level_2), (Total, Unnamed: 22_level_1, Unnamed: 22_level_2), (of which private, individuals, Unnamed: 23_level_2)]
Index: []

[0 rows x 24 columns]

In [9]:
df06=cleaned_dfs['2006']

In [10]:
df06

           Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
           Unnamed: 0_level_1 Unnamed: 1_level_1 Unnamed: 2_level_1
           Unnamed: 0_level_2 Unnamed: 1_level_2 Unnamed: 2_level_2
1                       Total            41989.0              121.0
3          Lake Geneva region             8022.0               16.0
4                       Waadt             4240.0               14.0
5                      Wallis             2621.0                1.0
6                      Geneva             1161.0                1.0
8           Espace Mittelland             7847.0               19.0
9                        Bern             3792.0               17.0
10                   Freiburg             2065.0                1.0
11                  Solothurn             1248.0                0.0
12                  Neuenburg              506.0                1.0
13                       Jura              236.0                0.0
15  North-western Switzerland             6032.0                2.0
16                Basel-Stadt              381.0                0.0
17           Basel-Landschaft             1481.0                0.0
18                     Aargau             4170.0                2.0
20                     Zurich             7878.0                0.0
22        Eastern Switzerland             5892.0               17.0
23                     Glarus              120.0                0.0
24               Schaffhausen              294.0                0.0
25           Appenzell A. Rh.              150.0                0.0
26           Appenzell I. Rh.               73.0                0.0
27                 St. Gallen             2101.0                4.0
28                 Graubünden             1550.0               13.0
29                    Thurgau             1604.0                0.0
31        Central Switzerland             4792.0               67.0
32                    Lucerne             1955.0               19.0
33                        Uri              193.0                0.0
34                     Schwyz             1277.0               38.0
35                   Obwalden              192.0                1.0
36                  Nidwalden              332.0                0.0
37                        Zug              843.0                9.0
39                     Ticino             1526.0                0.0

              Confed-            Cantons             Munic-  \
              eration Unnamed: 4_level_1          ipalities
   Unnamed: 3_level_2 Unnamed: 4_level_2 Unnamed: 5_level_2
1                 0.0                2.0              119.0
3                 0.0                1.0               15.0
4                 0.0                0.0               14.0
5                 0.0                0.0                1.0
6                 0.0                1.0                0.0
8                 0.0                0.0               19.0
9                 0.0                0.0               17.0
10                0.0                0.0                1.0
11                0.0                0.0                0.0
12                0.0                0.0                1.0
13                0.0                0.0                0.0
15                0.0                0.0                2.0
16                0.0                0.0                0.0
17                0.0                0.0                0.0
18                0.0                0.0                2.0
20                0.0                0.0                0.0
22                0.0                0.0               17.0
23                0.0                0.0                0.0
24                0.0                0.0                0.0
25                0.0                0.0                0.0
26                0.0                0.0                0.0
27                0.0                0.0                4.0
28                0.0                0.0               13.0
29                0.0                0.0                0.0
31                0.0                1.0               66.0
32                0.0                1.0               18.0
33                0.0                0.0                0.0
34                0.0                0.0               38.0
35                0.0                0.0                1.0
36                0.0                0.0                0.0
37                0.0                0.0                9.0
39                0.0                0.0                0.0

                                                      Total  \
                                         Unnamed: 8_level_1
   Unnamed: 6_level_2 Unnamed: 7_level_2 Unnamed: 8_level_2
1             41868.0             1764.0            15064.0
3              8006.0              331.0             2285.0
4              4226.0              150.0             1251.0
5              2620.0               18.0              474.0
6              1160.0              163.0              560.0
8              7828.0              344.0             2404.0
9              3775.0               43.0             1299.0
10             2064.0               78.0              689.0
11             1248.0              202.0              265.0
12              505.0               16.0              143.0
13              236.0                5.0                8.0
15             6030.0              394.0             2494.0
16              381.0               62.0              194.0
17             1481.0               76.0              791.0
18             4168.0              256.0             1509.0
20             7878.0              448.0             3834.0
22             5875.0              150.0             2121.0
23              120.0                0.0               51.0
24              294.0                0.0              123.0
25              150.0                0.0                5.0
26               73.0                0.0               18.0
27             2097.0              117.0              750.0
28             1537.0               33.0              568.0
29             1604.0                0.0              606.0
31             4725.0               97.0             1699.0
32             1936.0               51.0              598.0
33              193.0                0.0               81.0
34             1239.0                0.0              393.0
35              191.0                0.0               78.0
36              332.0               46.0              138.0
37              834.0                0.0              411.0
39             1526.0                0.0              227.0

    of which building               Total    of which private
         cooperatives Unnamed: 10_level_1         individuals
   Unnamed: 9_level_2 Unnamed: 10_level_2 Unnamed: 11_level_2
1              1259.0             25040.0             16733.0
3               425.0              5390.0              4050.0
4               250.0              2825.0              2214.0
5                31.0              2128.0              1611.0
6               144.0               437.0               225.0
8               146.0              5080.0              3266.0
9                55.0              2433.0              1262.0
10               67.0              1297.0              1019.0
11               24.0               781.0               524.0
12                0.0               346.0               284.0
13                0.0               223.0               177.0
15               47.0              3142.0              1807.0
16                0.0               125.0                40.0
17               10.0               614.0               549.0
18               37.0              2403.0              1218.0
20              452.0              3596.0              2112.0
22               93.0              3604.0              2653.0
23                0.0                69.0                52.0
24                0.0               171.0                85.0
25                3.0               145.0                59.0
26               12.0                55.0                48.0
27                0.0              1230.0              1068.0
28               25.0               936.0               686.0
29               53.0               998.0               655.0
31               92.0              2929.0              1889.0
32               49.0              1287.0               806.0
33                0.0               112.0                74.0
34               37.0               846.0               615.0
35                0.0               113.0                82.0
36                0.0               148.0                99.0
37                6.0               423.0               213.0
39                4.0              1299.0               956.0

In [11]:
df03=cleaned_dfs['2003']

In [12]:
df03

           Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
           Unnamed: 0_level_1 Unnamed: 1_level_1 Unnamed: 2_level_1
           Unnamed: 0_level_2 Unnamed: 1_level_2 Unnamed: 2_level_2
1                       Total            32096.0              310.0
3          Lake Geneva region             5383.0              138.0
4                       Waadt             2607.0               13.0
5                      Wallis             1570.0               18.0
6                      Geneva             1206.0              107.0
8           Espace Mittelland             5568.0               59.0
9                        Bern             3132.0               33.0
10                   Freiburg             1262.0                0.0
11                  Solothurn              774.0               24.0
12                  Neuenburg              218.0                0.0
13                       Jura              182.0                2.0
15  North-western Switzerland             4199.0               14.0
16                Basel-Stadt              210.0                9.0
17           Basel-Landschaft             1183.0                0.0
18                     Aargau             2806.0                5.0
20                     Zurich             7650.0                6.0
22        Eastern Switzerland             4230.0               46.0
23                     Glarus               68.0                0.0
24               Schaffhausen              178.0                0.0
25           Appenzell A. Rh.               79.0                0.0
26           Appenzell I. Rh.               36.0                0.0
27                 St. Gallen             1801.0               37.0
28                 Graubünden             1255.0                0.0
29                    Thurgau              813.0                9.0
31        Central Switzerland             3890.0               47.0
32                    Lucerne             1675.0                2.0
33                        Uri              115.0                0.0
34                     Schwyz              891.0               10.0
35                   Obwalden              202.0               33.0
36                  Nidwalden              147.0                0.0
37                        Zug              860.0                2.0
39                     Ticino             1176.0                0.0

              Confed-            Cantons             Munic-  \
              eration Unnamed: 4_level_1          ipalities
   Unnamed: 3_level_2 Unnamed: 4_level_2 Unnamed: 5_level_2
1                 1.0              118.0              191.0
3                 0.0               68.0               70.0
4                 0.0                0.0               13.0
5                 0.0                0.0               18.0
6                 0.0               68.0               39.0
8                 1.0                5.0               53.0
9                 1.0                4.0               28.0
10                0.0                0.0                0.0
11                0.0                1.0               23.0
12                0.0                0.0                0.0
13                0.0                0.0                2.0
15                0.0                9.0                5.0
16                0.0                9.0                0.0
17                0.0                0.0                0.0
18                0.0                0.0                5.0
20                0.0                0.0                6.0
22                0.0               36.0               10.0
23                0.0                0.0                0.0
24                0.0                0.0                0.0
25                0.0                0.0                0.0
26                0.0                0.0                0.0
27                0.0               36.0                1.0
28                0.0                0.0                0.0
29                0.0                0.0                9.0
31                0.0                0.0               47.0
32                0.0                0.0                2.0
33                0.0                0.0                0.0
34                0.0                0.0               10.0
35                0.0                0.0               33.0
36                0.0                0.0                0.0
37                0.0                0.0                2.0
39                0.0                0.0                0.0

                                                      Total  \
                                         Unnamed: 8_level_1
   Unnamed: 6_level_2 Unnamed: 7_level_2 Unnamed: 8_level_2
1             31786.0              968.0            11086.0
3              5245.0               84.0             1815.0
4              2594.0               69.0              788.0
5              1552.0                3.0              280.0
6              1099.0               12.0              747.0
8              5509.0               72.0             1693.0
9              3099.0               32.0             1042.0
10             1262.0               40.0              501.0
11              750.0                0.0              101.0
12              218.0                0.0               36.0
13              180.0                0.0               13.0
15             4185.0              199.0             1774.0
16              201.0                0.0              100.0
17             1183.0              130.0              371.0
18             2801.0               69.0             1303.0
20             7644.0              279.0             3254.0
22             4184.0               54.0             1429.0
23               68.0                0.0                4.0
24              178.0                0.0               36.0
25               79.0                0.0               15.0
26               36.0                0.0                3.0
27             1764.0                7.0              733.0
28             1255.0               27.0              452.0
29              804.0               20.0              186.0
31             3843.0              280.0              936.0
32             1673.0              163.0              401.0
33              115.0                0.0               20.0
34              881.0              117.0              204.0
35              169.0                0.0               55.0
36              147.0                0.0               39.0
37              858.0                0.0              217.0
39             1176.0                0.0              185.0

    of which building               Total    of which private
         cooperatives Unnamed: 10_level_1         individuals
   Unnamed: 9_level_2 Unnamed: 10_level_2 Unnamed: 11_level_2
1               837.0             19732.0             14131.0
3                43.0              3346.0              2931.0
4                29.0              1737.0              1520.0
5                14.0              1269.0              1121.0
6                 0.0               340.0               290.0
8                38.0              3744.0              2692.0
9                29.0              2025.0              1189.0
10                0.0               721.0               636.0
11                9.0               649.0               535.0
12                0.0               182.0               172.0
13                0.0               167.0               160.0
15               75.0              2212.0              1410.0
16                0.0               101.0                12.0
17               18.0               682.0               515.0
18               57.0              1429.0               883.0
20              527.0              4111.0              2175.0
22               75.0              2701.0              2126.0
23                0.0                64.0                58.0
24                0.0               142.0                87.0
25                1.0                64.0                54.0
26                0.0                33.0                26.0
27               58.0              1024.0               821.0
28               16.0               776.0               623.0
29                0.0               598.0               457.0
31               79.0              2627.0              1813.0
32               78.0              1109.0               694.0
33                0.0                95.0                70.0
34                0.0               560.0               433.0
35                1.0               114.0               100.0
36                0.0               108.0                76.0
37                0.0               641.0               440.0
39                0.0               991.0               984.0

In [13]:
df98=cleaned_dfs['1998']

In [14]:
df98

           Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
           Unnamed: 0_level_1 Unnamed: 1_level_1 Unnamed: 2_level_1
           Unnamed: 0_level_2 Unnamed: 1_level_2 Unnamed: 2_level_2
2                       Total            33734.0              569.0
4          Lake Geneva region             5156.0              284.0
5                       Waadt             2250.0               84.0
6                      Wallis             1405.0                5.0
7                      Geneva             1501.0              195.0
9           Espace Mittelland             6131.0               60.0
10                       Bern             3520.0                5.0
11                   Freiburg             1188.0               33.0
12                  Solothurn              912.0                1.0
13                  Neuenburg              330.0               21.0
14                       Jura              181.0                0.0
16  North-western Switzerland             5331.0               14.0
17                Basel-Stadt              208.0                0.0
18           Basel-Landschaft             1604.0                5.0
19                     Aargau             3519.0                9.0
21                     Zurich             6671.0               44.0
23        Eastern Switzerland             5059.0               87.0
24                     Glarus               77.0                0.0
25               Schaffhausen              203.0                2.0
26           Appenzell A. Rh.              159.0                0.0
27           Appenzell I. Rh.               20.0                0.0
28                 St. Gallen             1985.0                0.0
29                 Graubünden             1283.0               78.0
30                    Thurgau             1332.0                7.0
32        Central Switzerland             4219.0               64.0
33                    Lucerne             1732.0                9.0
34                        Uri              245.0                0.0
35                     Schwyz             1036.0               39.0
36                   Obwalden              197.0                4.0
37                  Nidwalden              435.0                4.0
38                        Zug              574.0                8.0

              Confed-            Cantons             Munic-  \
              eration Unnamed: 4_level_1          ipalities
   Unnamed: 3_level_2 Unnamed: 4_level_2 Unnamed: 5_level_2
2                 8.0              168.0              393.0
4                 5.0              108.0              171.0
5                 0.0               52.0               32.0
6                 5.0                0.0                0.0
7                 0.0               56.0              139.0
9                 0.0                1.0               59.0
10                0.0                0.0                5.0
11                0.0                1.0               32.0
12                0.0                0.0                1.0
13                0.0                0.0               21.0
14                0.0                0.0                0.0
16                3.0                4.0                7.0
17                0.0                0.0                0.0
18                0.0                0.0                5.0
19                3.0                4.0                2.0
21                0.0                6.0               38.0
23                0.0               41.0               46.0
24                0.0                0.0                0.0
25                0.0                0.0                2.0
26                0.0                0.0                0.0
27                0.0                0.0                0.0
28                0.0                0.0                0.0
29                0.0               41.0               37.0
30                0.0                0.0                7.0
32                0.0                8.0               56.0
33                0.0                0.0                9.0
34                0.0                0.0                0.0
35                0.0                0.0               39.0
36                0.0                0.0                4.0
37                0.0                0.0                4.0
38                0.0                8.0                0.0

                                                      Total    of which   \
                                         Unnamed: 8_level_1     building
   Unnamed: 6_level_2 Unnamed: 7_level_2 Unnamed: 8_level_2 cooperatives
2             33165.0             1854.0            12121.0       1057.0
4              4872.0              360.0             1913.0         62.0
5              2166.0              281.0              781.0         62.0
6              1400.0               79.0              230.0          0.0
7              1306.0                0.0              902.0          0.0
9              6071.0              376.0             2024.0        114.0
10             3515.0              210.0             1201.0         85.0
11             1155.0               36.0              475.0          0.0
12              911.0                0.0              261.0          2.0
13              309.0              130.0               38.0          0.0
14              181.0                0.0               49.0         27.0
16             5317.0              431.0             2053.0        231.0
17              208.0               46.0               98.0          0.0
18             1599.0              262.0              471.0         84.0
19             3510.0              123.0             1484.0        147.0
21             6627.0              449.0             2843.0        413.0
23             4972.0               86.0             1796.0        136.0
24               77.0                0.0               29.0          0.0
25              201.0                0.0               40.0          0.0
26              159.0                0.0               50.0          0.0
27               20.0                0.0                2.0          0.0
28             1985.0               78.0              831.0         80.0
29             1205.0                3.0              371.0         19.0
30             1325.0                5.0              473.0         37.0
32             4155.0              152.0             1301.0        101.0
33             1723.0              119.0              548.0         61.0
34              245.0                0.0               63.0         26.0
35              997.0                0.0              282.0          1.0
36              193.0               12.0               24.0          4.0
37              431.0               21.0              175.0          9.0
38              566.0                0.0              209.0          0.0

                 Total   of which
   Unnamed: 10_level_1     private
   Unnamed: 10_level_2 individuals
2              14497.0      4693.0
4               2241.0       358.0
5                918.0       186.0
6               1040.0        51.0
7                283.0       121.0
9               2812.0       859.0
10              1382.0       722.0
11               584.0        60.0
12               586.0        64.0
13               129.0        12.0
14               131.0         1.0
16              2085.0       748.0
17                58.0         6.0
18               791.0        75.0
19              1236.0       667.0
21              2265.0      1070.0
23              2185.0       905.0
24                45.0         3.0
25               119.0        42.0
26                85.0        24.0
27                17.0         1.0
28               752.0       324.0
29               574.0       257.0
30               593.0       254.0
32              2028.0       674.0
33               855.0       201.0
34               112.0        70.0
35               547.0       168.0
36                93.0        64.0
37               204.0        31.0
38               217.0       140.0

In [15]:
df03.columns

MultiIndex([('Unnamed: 0_level_0',  'Unnamed: 0_level_1', ...),
            ('Unnamed: 1_level_0',  'Unnamed: 1_level_1', ...),
            ('Unnamed: 2_level_0',  'Unnamed: 2_level_1', ...),
            (           'Confed-',             'eration', ...),
            (           'Cantons',  'Unnamed: 4_level_1', ...),
            (            'Munic-',           'ipalities', ...),
            (            'Munic-',           'ipalities', ...),
            (            'Munic-',           'ipalities', ...),
            (             'Total',  'Unnamed: 8_level_1', ...),
            ( 'of which building',        'cooperatives', ...),
            (             'Total', 'Unnamed: 10_level_1', ...),
            (  'of which private',         'individuals', ...)],
           )

In [16]:
# Display the first column name tuple from a MultiIndex DataFrame
first_column_name = df03.columns[0]
print(f"The name of the first column is: {first_column_name}")

The name of the first column is: ('Unnamed: 0_level_0', 'Unnamed: 0_level_1', 'Unnamed: 0_level_2')

In [17]:
# Display the first column name tuple from a MultiIndex DataFrame
first_column_name = df03.columns[6]
print(f"The name of the first column is: {first_column_name}")

The name of the first column is: ('Munic-', 'ipalities', 'Unnamed: 6_level_2')

In [18]:
# Flatten the multi-level column headers into single-level names
df03.columns = ['_'.join(col).strip() for col in df03.columns]

# Now rename the columns using the flattened single-level names
df03.rename(columns={'Unnamed: 0_level_0_Unnamed: 0_level_1_Unnamed: 0_level_2': 'Canton',
                   'Unnamed: 1_level_0_Unnamed: 1_level_1_Unnamed: 1_level_2': 'Overall Total',
                    'Unnamed: 2_level_0_Unnamed: 2_level_1_Unnamed: 2_level_2': 'Total Government Funded Projects',
                    'Munic-_ipalities_Unnamed: 6_level_2': 'Total Privately Funded Projects'}, inplace=True)

In [19]:
df03

,Canton,Overall Total,Total Government Funded Projects,Confed-_eration_Unnamed: 3_level_2,Cantons_Unnamed: 4_level_1_Unnamed: 4_level_2,Munic-_ipalities_Unnamed: 5_level_2,Total Privately Funded Projects,Munic-_ipalities_Unnamed: 7_level_2,Total_Unnamed: 8_level_1_Unnamed: 8_level_2,of which building_cooperatives_Unnamed: 9_level_2,Total_Unnamed: 10_level_1_Unnamed: 10_level_2,of which private_individuals_Unnamed: 11_level_2
1,Total,32096.0,310.0,1.0,118.0,191.0,31786.0,968.0,11086.0,837.0,19732.0,14131.0
3,Lake Geneva region,5383.0,138.0,0.0,68.0,70.0,5245.0,84.0,1815.0,43.0,3346.0,2931.0
4,Waadt,2607.0,13.0,0.0,0.0,13.0,2594.0,69.0,788.0,29.0,1737.0,1520.0
5,Wallis,1570.0,18.0,0.0,0.0,18.0,1552.0,3.0,280.0,14.0,1269.0,1121.0
6,Geneva,1206.0,107.0,0.0,68.0,39.0,1099.0,12.0,747.0,0.0,340.0,290.0
8,Espace Mittelland,5568.0,59.0,1.0,5.0,53.0,5509.0,72.0,1693.0,38.0,3744.0,2692.0
9,Bern,3132.0,33.0,1.0,4.0,28.0,3099.0,32.0,1042.0,29.0,2025.0,1189.0
10,Freiburg,1262.0,0.0,0.0,0.0,0.0,1262.0,40.0,501.0,0.0,721.0,636.0
11,Solothurn,774.0,24.0,0.0,1.0,23.0,750.0,0.0,101.0,9.0,649.0,535.0
12,Neuenburg,218.0,0.0,0.0,0.0,0.0,218.0,0.0,36.0,0.0,182.0,172.0
13,Jura,182.0,2.0,0.0,0.0,2.0,180.0,0.0,13.0,0.0,167.0,160.0
15,North-western Switzerland,4199.0,14.0,0.0,9.0,5.0,4185.0,199.0,1774.0,75.0,2212.0,1410.0
16,Basel-Stadt,210.0,9.0,0.0,9.0,0.0,201.0,0.0,100.0,0.0,101.0,12.0
17,Basel-Landschaft,1183.0,0.0,0.0,0.0,0.0,1183.0,130.0,371.0,18.0,682.0,515.0
18,Aargau,2806.0,5.0,0.0,0.0,5.0,2801.0,69.0,1303.0,57.0,1429.0,883.0
20,Zurich,7650.0,6.0,0.0,0.0,6.0,7644.0,279.0,3254.0,527.0,4111.0,2175.0
22,Eastern Switzerland,4230.0,46.0,0.0,36.0,10.0,4184.0,54.0,1429.0,75.0,2701.0,2126.0
23,Glarus,68.0,0.0,0.0,0.0,0.0,68.0,0.0,4.0,0.0,64.0,58.0
24,Schaffhausen,178.0,0.0,0.0,0.0,0.0,178.0,0.0,36.0,0.0,142.0,87.0
25,Appenzell A. Rh.,79.0,0.0,0.0,0.0,0.0,79.0,0.0,15.0,1.0,64.0,54.0
26,Appenzell I. Rh.,36.0,0.0,0.0,0.0,0.0,36.0,0.0,3.0,0.0,33.0,26.0
27,St. Gallen,1801.0,37.0,0.0,36.0,1.0,1764.0,7.0,733.0,58.0,1024.0,821.0
28,Graubünden,1255.0,0.0,0.0,0.0,0.0,1255.0,27.0,452.0,16.0,776.0,623.0
29,Thurgau,813.0,9.0,0.0,0.0,9.0,804.0,20.0,186.0,0.0,598.0,457.0
31,Central Switzerland,3890.0,47.0,0.0,0.0,47.0,3843.0,280.0,936.0,79.0,2627.0,1813.0
32,Lucerne,1675.0,2.0,0.0,0.0,2.0,1673.0,163.0,401.0,78.0,1109.0,694.0
33,Uri,115.0,0.0,0.0,0.0,0.0,115.0,0.0,20.0,0.0,95.0,70.0
34,Schwyz,891.0,10.0,0.0,0.0,10.0,881.0,117.0,204.0,0.0,560.0,433.0
35,Obwalden,202.0,33.0,0.0,0.0,33.0,169.0,0.0,55.0,1.0,114.0,100.0
36,Nidwalden,147.0,0.0,0.0,0.0,0.0,147.0,0.0,39.0,0.0,108.0,76.0
37,Zug,860.0,2.0,0.0,0.0,2.0,858.0,0.0,217.0,0.0,641.0,440.0
39,Ticino,1176.0,0.0,0.0,0.0,0.0,1176.0,0.0,185.0,0.0,991.0,984.0

In [20]:
# Select only the specified columns using .loc
df03_subset = df03.loc[:, ['Canton', 'Overall Total', 'Total Government Funded Projects', 'Total Privately Funded Projects']]


df03_subset

,Canton,Overall Total,Total Government Funded Projects,Total Privately Funded Projects
1,Total,32096.0,310.0,31786.0
3,Lake Geneva region,5383.0,138.0,5245.0
4,Waadt,2607.0,13.0,2594.0
5,Wallis,1570.0,18.0,1552.0
6,Geneva,1206.0,107.0,1099.0
8,Espace Mittelland,5568.0,59.0,5509.0
9,Bern,3132.0,33.0,3099.0
10,Freiburg,1262.0,0.0,1262.0
11,Solothurn,774.0,24.0,750.0
12,Neuenburg,218.0,0.0,218.0
13,Jura,182.0,2.0,180.0
15,North-western Switzerland,4199.0,14.0,4185.0
16,Basel-Stadt,210.0,9.0,201.0
17,Basel-Landschaft,1183.0,0.0,1183.0
18,Aargau,2806.0,5.0,2801.0
20,Zurich,7650.0,6.0,7644.0
22,Eastern Switzerland,4230.0,46.0,4184.0
23,Glarus,68.0,0.0,68.0
24,Schaffhausen,178.0,0.0,178.0
25,Appenzell A. Rh.,79.0,0.0,79.0
26,Appenzell I. Rh.,36.0,0.0,36.0
27,St. Gallen,1801.0,37.0,1764.0
28,Graubünden,1255.0,0.0,1255.0
29,Thurgau,813.0,9.0,804.0
31,Central Switzerland,3890.0,47.0,3843.0
32,Lucerne,1675.0,2.0,1673.0
33,Uri,115.0,0.0,115.0
34,Schwyz,891.0,10.0,881.0
35,Obwalden,202.0,33.0,169.0
36,Nidwalden,147.0,0.0,147.0
37,Zug,860.0,2.0,858.0
39,Ticino,1176.0,0.0,1176.0

In [21]:
df22=cleaned_dfs['2022 (new survey)']
df21=cleaned_dfs['2021 (new survey)']
df20=cleaned_dfs['2020 (new survey)']
df19=cleaned_dfs['2019 (new survey)']
df18=cleaned_dfs['2018 (new survey)']
df17=cleaned_dfs['2017 (new survey)']
df16=cleaned_dfs['2016 (new survey)']
df15=cleaned_dfs['2015 (new survey)']
df14=cleaned_dfs['2014 (new survey)']
df13=cleaned_dfs['2013 (new survey)']
df12=cleaned_dfs['2012 (new survey)']
df11=cleaned_dfs['2011']
df10=cleaned_dfs['2010']
df09=cleaned_dfs['2009']
df08=cleaned_dfs['2008']
df07=cleaned_dfs['2007']
df06=cleaned_dfs['2006']
df05=cleaned_dfs['2005']
df04=cleaned_dfs['2004']
df03=cleaned_dfs['2003']
df02=cleaned_dfs['2002']
df01=cleaned_dfs['2001']
df00=cleaned_dfs['2000']
df99=cleaned_dfs['1999']
df98=cleaned_dfs['1998']

In [22]:
df07

Empty DataFrame
Columns: [(Unnamed: 0_level_0, Unnamed: 0_level_1, Unnamed: 0_level_2), (Unnamed: 1_level_0, Unnamed: 1_level_1, Unnamed: 1_level_2), (Unnamed: 2_level_0, Unnamed: 2_level_1, Unnamed: 2_level_2), (Unnamed: 3_level_0, Unnamed: 3_level_1, Unnamed: 3_level_2), (Unnamed: 4_level_0, Unnamed: 4_level_1, Unnamed: 4_level_2), (Unnamed: 5_level_0, Unnamed: 5_level_1, Unnamed: 5_level_2), (Unnamed: 6_level_0, Unnamed: 6_level_1, Unnamed: 6_level_2), (Confed-, eration, Unnamed: 7_level_2), (Confed-, eration, Unnamed: 8_level_2), (Cantons, Unnamed: 9_level_1, Unnamed: 9_level_2), (Cantons, Unnamed: 10_level_1, Unnamed: 10_level_2), (Munic-, ipalities, Unnamed: 11_level_2), (Munic-, ipalities, Unnamed: 12_level_2), (Munic-, ipalities, Unnamed: 13_level_2), (Munic-, ipalities, Unnamed: 14_level_2), (Munic-, ipalities, Unnamed: 15_level_2), (Munic-, ipalities, Unnamed: 16_level_2), (Total, Unnamed: 17_level_1, Unnamed: 17_level_2), (Total, Unnamed: 18_level_1, Unnamed: 18_level_2), (of which building, cooperatives, Unnamed: 19_level_2), (of which building, cooperatives, Unnamed: 20_level_2), (Total, Unnamed: 21_level_1, Unnamed: 21_level_2), (Total, Unnamed: 22_level_1, Unnamed: 22_level_2), (of which private, individuals, Unnamed: 23_level_2)]
Index: []

[0 rows x 24 columns]

In [23]:
import pandas as pd

# Updated dictionary with all DataFrames defined above
dataframes = {
    'df98': df98,
    'df99': df99,
    'df00': df00,
    'df01': df01,
    'df02': df02,
    'df03': df03,
    'df04': df04,
    'df05': df05,
    'df06': df06,
    # 'df07': df07,
    # 'df08': df08,
    # 'df09': df09,
    # 'df10': df10,
    # 'df11': df11,
    # 'df12': df12,
    # 'df13': df13,
    # 'df14': df14,
    # 'df15': df15,
    # 'df16': df16,
    # 'df17': df17,
    # 'df18': df18,
    # 'df19': df19,
    # 'df20': df20,
    # 'df21': df21,
    # 'df22': df22,
}




# Define a function to flatten, rename columns, and handle errors
def process_dataframe(df):
    # Flatten the multi-level column headers into single-level names
    df.columns = ['_'.join(col).strip() for col in df.columns]

    # Rename the columns using the flattened single-level names
    df.rename(columns={
        'Unnamed: 0_level_0_Unnamed: 0_level_1_Unnamed: 0_level_2': 'Canton',
        'Unnamed: 1_level_0_Unnamed: 1_level_1_Unnamed: 1_level_2': 'Overall Total',
        'Unnamed: 2_level_0_Unnamed: 2_level_1_Unnamed: 2_level_2': 'Total Government Funded Projects',
        'Munic-_ipalities_Unnamed: 6_level_2': 'Total Privately Funded Projects'
    }, inplace=True)

    # Define the columns to select
    required_columns = ['Canton', 'Overall Total', 'Total Government Funded Projects', 'Total Privately Funded Projects']
    
    # Check if all required columns are in the DataFrame
    if all(col in df.columns for col in required_columns):
        # Select only the specified columns using .loc
        df_subset = df.loc[:, required_columns]
        return df_subset
    else:
        print(f"Warning: One or more required columns not found in the DataFrame. Skipping DataFrame:\n{df.columns.tolist()}\n")
        return None

# Apply the function to each DataFrame in the dictionary and filter out any None values
processed_dfs = {name: process_dataframe(df) for name, df in dataframes.items() if process_dataframe(df) is not None}

# Display the processed DataFrames for verification
for name, df in processed_dfs.items():
    print(f"Processed DataFrame for {name}:\n{df.head()}\n")

Warning: One or more required columns not found in the DataFrame. Skipping DataFrame:
['C_a_n_t_o_n', 'O_v_e_r_a_l_l_ _T_o_t_a_l', 'T_o_t_a_l_ _G_o_v_e_r_n_m_e_n_t_ _F_u_n_d_e_d_ _P_r_o_j_e_c_t_s', 'C_o_n_f_e_d_-___e_r_a_t_i_o_n___U_n_n_a_m_e_d_:_ _3___l_e_v_e_l___2', 'C_a_n_t_o_n_s___U_n_n_a_m_e_d_:_ _4___l_e_v_e_l___1___U_n_n_a_m_e_d_:_ _4___l_e_v_e_l___2', 'M_u_n_i_c_-___i_p_a_l_i_t_i_e_s___U_n_n_a_m_e_d_:_ _5___l_e_v_e_l___2', 'T_o_t_a_l_ _P_r_i_v_a_t_e_l_y_ _F_u_n_d_e_d_ _P_r_o_j_e_c_t_s', 'M_u_n_i_c_-___i_p_a_l_i_t_i_e_s___U_n_n_a_m_e_d_:_ _7___l_e_v_e_l___2', 'T_o_t_a_l___U_n_n_a_m_e_d_:_ _8___l_e_v_e_l___1___U_n_n_a_m_e_d_:_ _8___l_e_v_e_l___2', 'o_f_ _w_h_i_c_h_ ___b_u_i_l_d_i_n_g___c_o_o_p_e_r_a_t_i_v_e_s', 'T_o_t_a_l___U_n_n_a_m_e_d_:_ _1_0___l_e_v_e_l___1___U_n_n_a_m_e_d_:_ _1_0___l_e_v_e_l___2', 'o_f_ _w_h_i_c_h_ ___p_r_i_v_a_t_e___i_n_d_i_v_i_d_u_a_l_s']

Warning: One or more required columns not found in the DataFrame. Skipping DataFrame:
['C_a_n_t_o_n', 'O_v_e_r_a_l_l_ _T_o_t_a_l', 'T_o_t_a_l_ _G_o_v_e_r_n_m_e_n_t_ _F_u_n_d_e_d_ _P_r_o_j_e_c_t_s', 'C_o_n_f_e_d_-___e_r_a_t_i_o_n___U_n_n_a_m_e_d_:_ _3___l_e_v_e_l___2', 'C_a_n_t_o_n_s___U_n_n_a_m_e_d_:_ _4___l_e_v_e_l___1___U_n_n_a_m_e_d_:_ _4___l_e_v_e_l___2', 'M_u_n_i_c_-___i_p_a_l_i_t_i_e_s___U_n_n_a_m_e_d_:_ _5___l_e_v_e_l___2', 'T_o_t_a_l_ _P_r_i_v_a_t_e_l_y_ _F_u_n_d_e_d_ _P_r_o_j_e_c_t_s', 'M_u_n_i_c_-___i_p_a_l_i_t_i_e_s___U_n_n_a_m_e_d_:_ _7___l_e_v_e_l___2', 'T_o_t_a_l___U_n_n_a_m_e_d_:_ _8___l_e_v_e_l___1___U_n_n_a_m_e_d_:_ _8___l_e_v_e_l___2', 'o_f_ _w_h_i_c_h_ ___b_u_i_l_d_i_n_g___c_o_o_p_e_r_a_t_i_v_e_s', 'T_o_t_a_l___U_n_n_a_m_e_d_:_ _1_0___l_e_v_e_l___1___U_n_n_a_m_e_d_:_ _1_0___l_e_v_e_l___2', 'o_f_ _w_h_i_c_h_ ___p_r_i_v_a_t_e___i_n_d_i_v_i_d_u_a_l_s']

Warning: One or more required columns not found in the DataFrame. Skipping DataFrame:
['C_a_n_t_o_n', 'O_v_e_r_a_l_l_ _T_o_t_a_l', 'T_o_t_a_l_ _G_o_v_e_r_n_m_e_n_t_ _F_u_n_d_e_d_ _P_r_o_j_e_c_t_s', 'C_o_n_f_e_d_-___e_r_a_t_i_o_n___U_n_n_a_m_e_d_:_ _3___l_e_v_e_l___2', 'C_a_n_t_o_n_s___U_n_n_a_m_e_d_:_ _4___l_e_v_e_l___1___U_n_n_a_m_e_d_:_ _4___l_e_v_e_l___2', 'M_u_n_i_c_-___i_p_a_l_i_t_i_e_s___U_n_n_a_m_e_d_:_ _5___l_e_v_e_l___2', 'T_o_t_a_l_ _P_r_i_v_a_t_e_l_y_ _F_u_n_d_e_d_ _P_r_o_j_e_c_t_s', 'M_u_n_i_c_-___i_p_a_l_i_t_i_e_s___U_n_n_a_m_e_d_:_ _7___l_e_v_e_l___2', 'T_o_t_a_l___U_n_n_a_m_e_d_:_ _8___l_e_v_e_l___1___U_n_n_a_m_e_d_:_ _8___l_e_v_e_l___2', 'o_f_ _w_h_i_c_h_ ___b_u_i_l_d_i_n_g___c_o_o_p_e_r_a_t_i_v_e_s', 'T_o_t_a_l___U_n_n_a_m_e_d_:_ _1_0___l_e_v_e_l___1___U_n_n_a_m_e_d_:_ _1_0___l_e_v_e_l___2', 'o_f_ _w_h_i_c_h_ ___p_r_i_v_a_t_e___i_n_d_i_v_i_d_u_a_l_s']

Warning: One or more required columns not found in the DataFrame. Skipping DataFrame:
['C_a_n_t_o_n', 'O_v_e_r_a_l_l_ _T_o_t_a_l', 'T_o_t_a_l_ _G_o_v_e_r_n_m_e_n_t_ _F_u_n_d_e_d_ _P_r_o_j_e_c_t_s', 'C_o_n_f_e_d_-___e_r_a_t_i_o_n___U_n_n_a_m_e_d_:_ _3___l_e_v_e_l___2', 'C_a_n_t_o_n_s___U_n_n_a_m_e_d_:_ _4___l_e_v_e_l___1___U_n_n_a_m_e_d_:_ _4___l_e_v_e_l___2', 'M_u_n_i_c_-___i_p_a_l_i_t_i_e_s___U_n_n_a_m_e_d_:_ _5___l_e_v_e_l___2', 'T_o_t_a_l_ _P_r_i_v_a_t_e_l_y_ _F_u_n_d_e_d_ _P_r_o_j_e_c_t_s', 'M_u_n_i_c_-___i_p_a_l_i_t_i_e_s___U_n_n_a_m_e_d_:_ _7___l_e_v_e_l___2', 'T_o_t_a_l___U_n_n_a_m_e_d_:_ _8___l_e_v_e_l___1___U_n_n_a_m_e_d_:_ _8___l_e_v_e_l___2', 'o_f_ _w_h_i_c_h_ ___b_u_i_l_d_i_n_g___c_o_o_p_e_r_a_t_i_v_e_s', 'T_o_t_a_l___U_n_n_a_m_e_d_:_ _1_0___l_e_v_e_l___1___U_n_n_a_m_e_d_:_ _1_0___l_e_v_e_l___2', 'o_f_ _w_h_i_c_h_ ___p_r_i_v_a_t_e___i_n_d_i_v_i_d_u_a_l_s']

Warning: One or more required columns not found in the DataFrame. Skipping DataFrame:
['C_a_n_t_o_n', 'O_v_e_r_a_l_l_ _T_o_t_a_l', 'T_o_t_a_l_ _G_o_v_e_r_n_m_e_n_t_ _F_u_n_d_e_d_ _P_r_o_j_e_c_t_s', 'C_o_n_f_e_d_-___e_r_a_t_i_o_n___U_n_n_a_m_e_d_:_ _3___l_e_v_e_l___2', 'C_a_n_t_o_n_s___U_n_n_a_m_e_d_:_ _4___l_e_v_e_l___1___U_n_n_a_m_e_d_:_ _4___l_e_v_e_l___2', 'M_u_n_i_c_-___i_p_a_l_i_t_i_e_s___U_n_n_a_m_e_d_:_ _5___l_e_v_e_l___2', 'T_o_t_a_l_ _P_r_i_v_a_t_e_l_y_ _F_u_n_d_e_d_ _P_r_o_j_e_c_t_s', 'M_u_n_i_c_-___i_p_a_l_i_t_i_e_s___U_n_n_a_m_e_d_:_ _7___l_e_v_e_l___2', 'T_o_t_a_l___U_n_n_a_m_e_d_:_ _8___l_e_v_e_l___1___U_n_n_a_m_e_d_:_ _8___l_e_v_e_l___2', 'o_f_ _w_h_i_c_h_ ___b_u_i_l_d_i_n_g___c_o_o_p_e_r_a_t_i_v_e_s', 'T_o_t_a_l___U_n_n_a_m_e_d_:_ _1_0___l_e_v_e_l___1___U_n_n_a_m_e_d_:_ _1_0___l_e_v_e_l___2', 'o_f_ _w_h_i_c_h_ ___p_r_i_v_a_t_e___i_n_d_i_v_i_d_u_a_l_s']

Warning: One or more required columns not found in the DataFrame. Skipping DataFrame:
['C_a_n_t_o_n', 'O_v_e_r_a_l_l_ _T_o_t_a_l', 'T_o_t_a_l_ _G_o_v_e_r_n_m_e_n_t_ _F_u_n_d_e_d_ _P_r_o_j_e_c_t_s', 'C_o_n_f_e_d_-___e_r_a_t_i_o_n___U_n_n_a_m_e_d_:_ _3___l_e_v_e_l___2', 'C_a_n_t_o_n_s___U_n_n_a_m_e_d_:_ _4___l_e_v_e_l___1___U_n_n_a_m_e_d_:_ _4___l_e_v_e_l___2', 'M_u_n_i_c_-___i_p_a_l_i_t_i_e_s___U_n_n_a_m_e_d_:_ _5___l_e_v_e_l___2', 'T_o_t_a_l_ _P_r_i_v_a_t_e_l_y_ _F_u_n_d_e_d_ _P_r_o_j_e_c_t_s', 'M_u_n_i_c_-___i_p_a_l_i_t_i_e_s___U_n_n_a_m_e_d_:_ _7___l_e_v_e_l___2', 'T_o_t_a_l___U_n_n_a_m_e_d_:_ _8___l_e_v_e_l___1___U_n_n_a_m_e_d_:_ _8___l_e_v_e_l___2', 'o_f_ _w_h_i_c_h_ _b_u_i_l_d_i_n_g___c_o_o_p_e_r_a_t_i_v_e_s___U_n_n_a_m_e_d_:_ _9___l_e_v_e_l___2', 'T_o_t_a_l___U_n_n_a_m_e_d_:_ _1_0___l_e_v_e_l___1___U_n_n_a_m_e_d_:_ _1_0___l_e_v_e_l___2', 'o_f_ _w_h_i_c_h_ _p_r_i_v_a_t_e___i_n_d_i_v_i_d_u_a_l_s___U_n_n_a_m_e_d_:_ _1_1___l_e_v_e_l___2']

Warning: One or more required columns not found in the DataFrame. Skipping DataFrame:
['C_a_n_t_o_n', 'O_v_e_r_a_l_l_ _T_o_t_a_l', 'T_o_t_a_l_ _G_o_v_e_r_n_m_e_n_t_ _F_u_n_d_e_d_ _P_r_o_j_e_c_t_s', 'C_o_n_f_e_d_-___e_r_a_t_i_o_n___U_n_n_a_m_e_d_:_ _3___l_e_v_e_l___2', 'C_a_n_t_o_n_s___U_n_n_a_m_e_d_:_ _4___l_e_v_e_l___1___U_n_n_a_m_e_d_:_ _4___l_e_v_e_l___2', 'M_u_n_i_c_-___i_p_a_l_i_t_i_e_s___U_n_n_a_m_e_d_:_ _5___l_e_v_e_l___2', 'T_o_t_a_l_ _P_r_i_v_a_t_e_l_y_ _F_u_n_d_e_d_ _P_r_o_j_e_c_t_s', 'M_u_n_i_c_-___i_p_a_l_i_t_i_e_s___U_n_n_a_m_e_d_:_ _7___l_e_v_e_l___2', 'T_o_t_a_l___U_n_n_a_m_e_d_:_ _8___l_e_v_e_l___1___U_n_n_a_m_e_d_:_ _8___l_e_v_e_l___2', 'o_f_ _w_h_i_c_h_ _b_u_i_l_d_i_n_g___c_o_o_p_e_r_a_t_i_v_e_s___U_n_n_a_m_e_d_:_ _9___l_e_v_e_l___2', 'T_o_t_a_l___U_n_n_a_m_e_d_:_ _1_0___l_e_v_e_l___1___U_n_n_a_m_e_d_:_ _1_0___l_e_v_e_l___2', 'o_f_ _w_h_i_c_h_ _p_r_i_v_a_t_e___i_n_d_i_v_i_d_u_a_l_s___U_n_n_a_m_e_d_:_ _1_1___l_e_v_e_l___2']

Warning: One or more required columns not found in the DataFrame. Skipping DataFrame:
['C_a_n_t_o_n', 'O_v_e_r_a_l_l_ _T_o_t_a_l', 'T_o_t_a_l_ _G_o_v_e_r_n_m_e_n_t_ _F_u_n_d_e_d_ _P_r_o_j_e_c_t_s', 'C_o_n_f_e_d_-___e_r_a_t_i_o_n___U_n_n_a_m_e_d_:_ _3___l_e_v_e_l___2', 'C_a_n_t_o_n_s___U_n_n_a_m_e_d_:_ _4___l_e_v_e_l___1___U_n_n_a_m_e_d_:_ _4___l_e_v_e_l___2', 'M_u_n_i_c_-___i_p_a_l_i_t_i_e_s___U_n_n_a_m_e_d_:_ _5___l_e_v_e_l___2', 'T_o_t_a_l_ _P_r_i_v_a_t_e_l_y_ _F_u_n_d_e_d_ _P_r_o_j_e_c_t_s', 'M_u_n_i_c_-___i_p_a_l_i_t_i_e_s___U_n_n_a_m_e_d_:_ _7___l_e_v_e_l___2', 'T_o_t_a_l___U_n_n_a_m_e_d_:_ _8___l_e_v_e_l___1___U_n_n_a_m_e_d_:_ _8___l_e_v_e_l___2', 'o_f_ _w_h_i_c_h_ _b_u_i_l_d_i_n_g___c_o_o_p_e_r_a_t_i_v_e_s___U_n_n_a_m_e_d_:_ _9___l_e_v_e_l___2', 'T_o_t_a_l___U_n_n_a_m_e_d_:_ _1_0___l_e_v_e_l___1___U_n_n_a_m_e_d_:_ _1_0___l_e_v_e_l___2', 'o_f_ _w_h_i_c_h_ _p_r_i_v_a_t_e___i_n_d_i_v_i_d_u_a_l_s___U_n_n_a_m_e_d_:_ _1_1___l_e_v_e_l___2']

Warning: One or more required columns not found in the DataFrame. Skipping DataFrame:
['C_a_n_t_o_n', 'O_v_e_r_a_l_l_ _T_o_t_a_l', 'T_o_t_a_l_ _G_o_v_e_r_n_m_e_n_t_ _F_u_n_d_e_d_ _P_r_o_j_e_c_t_s', 'C_o_n_f_e_d_-___e_r_a_t_i_o_n___U_n_n_a_m_e_d_:_ _3___l_e_v_e_l___2', 'C_a_n_t_o_n_s___U_n_n_a_m_e_d_:_ _4___l_e_v_e_l___1___U_n_n_a_m_e_d_:_ _4___l_e_v_e_l___2', 'M_u_n_i_c_-___i_p_a_l_i_t_i_e_s___U_n_n_a_m_e_d_:_ _5___l_e_v_e_l___2', 'T_o_t_a_l_ _P_r_i_v_a_t_e_l_y_ _F_u_n_d_e_d_ _P_r_o_j_e_c_t_s', 'M_u_n_i_c_-___i_p_a_l_i_t_i_e_s___U_n_n_a_m_e_d_:_ _7___l_e_v_e_l___2', 'T_o_t_a_l___U_n_n_a_m_e_d_:_ _8___l_e_v_e_l___1___U_n_n_a_m_e_d_:_ _8___l_e_v_e_l___2', 'o_f_ _w_h_i_c_h_ _b_u_i_l_d_i_n_g___c_o_o_p_e_r_a_t_i_v_e_s___U_n_n_a_m_e_d_:_ _9___l_e_v_e_l___2', 'T_o_t_a_l___U_n_n_a_m_e_d_:_ _1_0___l_e_v_e_l___1___U_n_n_a_m_e_d_:_ _1_0___l_e_v_e_l___2', 'o_f_ _w_h_i_c_h_ _p_r_i_v_a_t_e___i_n_d_i_v_i_d_u_a_l_s___U_n_n_a_m_e_d_:_ _1_1___l_e_v_e_l___2']

/var/folders/j_/555m2zps099832fjh_m8jjnc0000gn/T/ipykernel_57149/3561601808.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={
/var/folders/j_/555m2zps099832fjh_m8jjnc0000gn/T/ipykernel_57149/3561601808.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={

AttributeError: 'NoneType' object has no attribute 'head'

In [ ]:
df00