In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../../../Cleaning/olympics/womens/cleaned_womens2012to2020ub')

In [3]:
df

,Rank,Gymnast,Nation,D Score,E Score,Pen.,Total,year
0,1,Aliya Mustafina,Russia,7.0,9.133,0.0,16.133,2012
1,2,He Kexin,China,7.1,8.833,0.0,15.933,2012
2,3,Beth Tweddle,Great Britain,7.0,8.916,0.0,15.916,2012
3,4,Yao Jinnan,China,6.8,8.966,0.0,15.766,2012
4,5,Viktoria Komova,Russia,7.0,8.666,0.0,15.666,2012
5,6,Elisabeth Seitz,Germany,6.7,8.566,0.0,15.266,2012
6,7,Kōko Tsurumi,Japan,6.4,8.566,0.0,14.966,2012
7,8,Gabby Douglas,United States,6.3,8.600,0.0,14.900,2012
8,1,Aliya Mustafina,RUS,6.8,9.100,0.0,15.900,2016
9,2,Madison Kocian,USA,6.7,9.133,0.0,15.833,2016
10,3,Sophie Scheder,GER,6.6,8.966,0.0,15.566,2016
11,4,Elisabeth Seitz,GER,6.6,8.933,0.0,15.533,2016
12,5,Shang Chunsong,CHN,6.7,8.733,0.0,15.433,2016
13,6,Jessica López,VEN,6.7,8.633,0.0,15.333,2016
14,7,Gabby Douglas,USA,6.5,8.566,0.0,15.066,2016
15,8,Daria Spiridonova,RUS,6.1,7.866,0.0,13.966,2016
16,1,Nina Derwael,BEL,6.7,8.500,0.0,15.200,2020
17,2,Anastasia Ilyankova,ROC,6.3,8.533,0.0,14.833,2020
18,3,Sunisa Lee,USA,6.2,8.300,0.0,14.500,2020
19,4,Lu Yufei,CHN,6.0,8.400,0.0,14.400,2020
20,5,Elisabeth Seitz,GER,6.2,8.200,0.0,14.400,2020
21,6,Mélanie de Jesus dos Santos,FRA,6.1,7.933,0.0,14.033,2020
22,7,Fan Yilin,CHN,6.4,7.500,0.0,13.900,2020
23,8,Angelina Melnikova,ROC,5.9,7.166,0.0,13.066,2020