In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("../Cleaning/Asian2023Championships/asia2023mens")

In [5]:
df

,Rank,Gymnast,Country,Apparatus,D Score,E Score,Pen.,Total
0,1,Carlos Yulo,FIL,FX,6.3,9.000,0,15.300
1,2,Dmitriy Patanin,KAZ,FX,5.9,8.466,0,14.366
2,3,Su Weide,CHN,FX,6.3,8.033,0,14.333
3,4,Fumiya Sasaki,JPN,FX,5.8,8.433,0,14.233
4,5,Milad Karimi,KAZ,FX,6.3,8.100,0,14.100
5,6,Shinnosuke Oka,JPN,FX,5.9,8.433,0,13.933
6,7,Ryu Sung-hyun,SK,FX,5.8,7.633,0,13.433
7,8,John Ivan Cruz,FIL,FX,5.5,5.933,0,11.433
8,1,Tian Hao,CHN,HB,6.4,8.133,0,14.533
9,2,Shinnosuke Oka,JPN,HB,5.5,8.866,0,14.366
10,3,Carlos Yulo,FIL,HB,5.4,8.633,0,14.033
11,4,Lee Chih-kai,TPE,HB,5.1,8.233,0,13.333
12,5,Rasuljon Abdurakhimov,UZB,HB,4.9,8.300,0,13.200
13,6,Takeru Kitazono,JPN,HB,5.4,7.366,0,12.766
14,7,Su Weide,CHN,HB,5.3,6.566,0,11.866
15,8,Milad Karimi,KAZ,HB,5.2,6.366,0,11.566
16,1,Carlos Yulo,FIL,PB,6.3,8.966,0,15.266
17,2,Shinnosuke Oka,JPN,PB,6.4,8.733,0,15.133
18,3,Yin Dehang,CHN,PB,6.4,8.700,0,15.100
19,4,Ryu Sung-hyun,SK,PB,5.6,8.833,0,14.433
20,5,Ryu Jae-ho,SK,PB,5.4,8.433,0,13.833
21,6,Takeru Kitazono,JPN,PB,5.2,7.600,0,12.800
22,7,Lan Xingyu,CHN,PB,5.9,6.833,0,12.733
23,8,Nguyễn Phước Hải,VIE,PB,5.5,7.133,0,12.633
24,1,Nariman Kurbanov,KAZ,PH,6.6,8.733,0,15.333
25,2,Ahmad Abu Al-Soud,JOR,PH,6.4,8.833,0,15.233
26,3,Ryota Tsumura,JPN,PH,6.6,8.433,0,15.033
27,4,Yin Dehang,CHN,PH,6.4,8.066,0,14.466
28,5,Shinnosuke Oka,JPN,PH,5.8,8.600,0,14.400
29,6,Tian Hao,CHN,PH,5.8,8.500,0,14.300
30,7,Khabibullo Ergashev,UZB,PH,5.5,8.300,0,13.800
31,8,Abdulla Azimov,UZB,PH,6.3,6.600,0,12.900
32,1,Lan Xingyu,CHN,SR,6.4,8.800,0,15.200
33,2,Nguyễn Văn Khánh Phong,VIE,SR,5.9,8.466,0,14.366
34,3,Ng Kiu Chung,HK,SR,5.7,8.400,0,14.100
35,4,Carlos Yulo,FIL,SR,5.7,8.333,0,14.033
36,5,Lin Guan-yi,TPE,SR,5.8,8.200,0,14.000
37,6,Shinnosuke Oka,JPN,SR,5.6,8.366,0,13.966
38,7,Lee Junghyo,SK,SR,5.3,8.500,0,13.800
39,8,Yin Dehang,CHN,SR,5.5,7.900,0,13.400

In [6]:
vt = pd.read_csv("../Cleaning/Asian2023Championships/asia2023vt")

In [7]:
iaa = pd.read_csv("../Cleaning/Asian2023Championships/asia2023iaa")

In [8]:
vt

,Rank,Gymnast,Country,vt1_D Score,vt_1E Score,vt1_Pen.,Score 1,vt2_D Score,vt2_E Score,vt_2Pen.,Score 2,Total
0,1,Carlos Yulo,FIL,5.6,8.366,0,13.966,5.6,9.033,0,14.633,14.299
1,2,Abdulaziz Mirvaliev,UZB,5.6,9.066,0,14.666,5.6,8.000,–0.1,13.500,14.083
2,3,Kim Jae-ho,SK,5.2,9.133,0,14.333,5.2,8.000,0,13.200,13.766
3,4,Tikumporn Surintornta,THA,5.2,8.033,0,13.233,5.2,8.900,0,14.100,13.667
4,5,Erkhembayar Usukhbayar,MGL,4.8,9.166,0,13.966,4.0,9.300,0,13.300,13.633
5,6,Muhammad Sharul Aimy,MAS,5.2,7.833,0,12.933,5.2,9.100,0,14.300,13.617
6,7,Ng Ka Ki,HK,5.6,7.766,0,13.366,5.2,8.600,0,13.800,13.583
7,8,Juancho Miguel Besana,FIL,5.6,7.933,0,13.233,5.2,8.700,–0.3,13.600,13.417

In [9]:
iaa

,Rank,Gymnast,Country,FX,PH,SR,VT,PB,HB,Total
0,1,Shinnosuke Oka,JPN,14.100,14.566,13.866,14.333,15.000,14.200,86.065
1,2,Carlos Yulo,FIL,14.966,13.266,14.300,14.866,15.066,13.466,85.930
2,3,Takeru Kitazono,JPN,13.900,14.333,13.433,14.366,14.966,14.433,85.431
3,4,Milad Karimi,KAZ,14.466,13.500,13.300,14.700,13.366,14.366,83.698
4,5,Tian Hao,CHN,13.933,14.166,13.200,13.766,13.466,15.100,83.631
5,6,Yin Dehang,CHN,13.433,14.300,13.666,13.900,14.900,13.000,83.199
6,7,Ryu Sung-hyun,SK,14.000,13.533,13.400,14.833,14.000,13.366,83.132
7,8,Khabibullo Ergashev,UZB,13.100,13.866,12.866,14.133,13.633,13.233,80.831