In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../../../Cleaning/olympics/mens/')

In [3]:
df

,Team,country,fx,ph,sr,vt,pb,hb
0,Denis Ablyazin,ROC,13.900,0.000,15.033,14.866,0.000,0.000
1,David Belyavskiy,ROC,0.000,14.841,0.000,0.000,15.333,14.166
2,Artur Dalaloyan,ROC,14.066,13.833,14.666,14.933,14.600,13.933
3,Nikita Nagornyy,ROC,14.666,14.466,14.700,14.966,15.166,14.366
4,Daiki Hashimoto,JPN,14.600,14.800,13.833,14.833,0.000,15.100
5,Kazuma Kaya,JPN,0.000,14.566,14.100,0.000,15.000,14.200
6,Takeru Kitazono,JPN,14.600,14.200,0.000,14.166,15.000,14.500
7,Wataru Tanigawa,JPN,14.500,0.000,14.500,15.233,14.666,0.000
8,Lin Chaopan,CHN,13.166,0.000,0.000,14.733,0.000,14.133
9,Sun Wei,CHN,14.366,15.000,14.233,14.866,14.800,14.200
10,Xiao Ruoteng,CHN,14.600,14.166,14.366,14.733,14.933,14.333
11,Zou Jingyuan,CHN,0.000,14.800,15.000,0.000,15.466,0.000
12,Joe Fraser,GBR,13.866,14.666,14.500,14.133,14.666,14.333
13,James Hall,GBR,14.033,14.000,13.600,14.233,13.100,14.200
14,Giarnni Regini-Moran,GBR,14.533,0.000,13.733,14.666,15.166,0.000
15,Max Whitlock,GBR,0.000,14.966,0.000,0.000,0.000,13.366
16,Brody Malone,USA,0.000,14.000,14.100,14.233,0.000,14.633
17,Sam Mikulak,USA,12.133,13.733,0.000,14.466,15.000,14.566
18,Yul Moldauer,USA,14.366,14.366,13.900,14.200,14.566,0.000
19,Shane Wiskus,USA,13.466,0.000,14.166,0.000,14.700,14.000
20,Christian Baumann,SUI,0.000,0.000,13.166,0.000,14.600,13.966
21,Pablo Br√§gger,SUI,14.233,13.400,13.466,13.833,14.833,13.933
22,Benjamin Gischard,SUI,14.000,13.866,0.000,14.000,0.000,0.000
23,Eddy Yusof,SUI,13.833,13.833,13.666,14.166,14.633,13.500
24,Illia Kovtun,UKR,13.800,14.200,0.000,0.000,13.233,14.433
25,Petro Pakhniuk,UKR,13.466,12.266,12.533,13.233,15.200,13.466
26,Igor Radivilov,UKR,0.000,0.000,14.633,14.600,0.000,0.000
27,Yevgen Yudenkov,UKR,13.966,13.533,13.700,13.666,13.800,12.666
28,Lukas Dauser,GER,11.500,12.100,0.000,13.700,15.466,13.600
29,Nils Dunkel,GER,0.000,13.700,13.600,0.000,12.733,13.033
30,Philipp Herder,GER,11.866,0.000,13.200,14.333,14.566,0.000
31,Andreas Toba,GER,11.466,13.400,13.533,14.333,0.000,12.366